### PR TITLE
Updated fitacf comments to use doxygen style

### PR DESCRIPTION
**Pull request by kkotyk**
I updated to doxygen style comments with more info in places. No changes to the algorithms. @pasha-ponomarenko perhaps you would like to add more detail in places about certain algorithms. 

I dont think this should need much for testing.

### CODE REVIEW

**Comment by egthomas** [comment]
@kkotyk , @pasha-ponomarenko - are you guys still working on the comments for this pull request?

**Comment by pasha-ponomarenko** [comment]
Still should add one or two more comments.

**Comment by egthomas** [comment]
@pasha-ponomarenko - still planning to add more comments?  Or can this be merged?

**Comment by pasha-ponomarenko** [comment]
I think now it is ready to go, although there seem to be some conflicts requirig resolution...

**Comment by egthomas** [comment]
I had commented out two unused variables within `preprocessing.c` which were producing compiler warnings (`int i=0;` in `Filter_Bad_ACFs` and `PHASENODE* phase_prev;` in `ACF_Phase_Unwrap`), but because the spacing had changed on this branch github thought there was a conflict.  Should be fixed now.

**Comment by pasha-ponomarenko** [comment]
Yep, it looks fine now. You can go ahead with merging.

**Pull request merged**
