### PR TITLE
Warning cleanup

### PR DESCRIPTION
**Pull request by egthomas**
This pull request represents an on-and-off effort to fix the various compiler warnings observed when executing the make.build and make.code commands during installation.  It is not a comprehensive solution but is a start.

### CODE REVIEW

**Comment by pasha-ponomarenko** [comment]
Any testing is required at this stage or  I can just merge this one and #109?

**Comment by egthomas** [comment]
Someone should probably verify that #109 fixes the compilation error, and then separately confirm that this pull request doesn't introduce any additional crashes. But i hope they should both be pretty benign.

**Comment by pasha-ponomarenko** [comment]
Keith is going to help with this...

**Comment by ksterne** [comment]
We should wait until after the 4.1 release (#110) is done to merge this in.

**Comment by pasha-ponomarenko** [comment]
> We should wait until after the 4.1 release (#110) is done to merge this in.

I am getting confused here. I thought that this should have been merged before ctreating the release branch...

**Comment by ksterne** [comment]
Sorry, I didn't think this was critical for the next release as I didn't see it apart of any of the goals or discussion in #95.  Is this something that **needs** to be in the next release?  Or can it wait until 4.2?  If it is desired that the `warning_cleanup` branch is apart of the 4.1 release, I can cherry pick this into #110 once it's merged into develop to keep the two branches sync'ed.

**Comment by egthomas** [comment]
The work is complete and there is no reason for it to sit for another 6+ months.  I've changed the base branch so it can be merged into the release branch and no cherry picking is necessary.

**Comment by egthomas** [comment]
@kkotyk any thoughts on this?

**Comment by kkotyk** [comment]
I would agree that these are small changes that probably don't need to wait if its not too much of a hassle. It will be nice for our users to have less warnings when compiling. Thanks for starting this in the first place @egthomas.

**Comment by pasha-ponomarenko** [comment]
So, looks like we should be OK with pushing thins into 4.1, @ksterne?

**Comment by ksterne** [comment]
If I'm in the minority I'll still protest.  Not everyone has to like it.

With this and #112, should I further delay the merge of #110?  Right now I've got it set for Dec. 12th.  I'd think we're still good for that date, but thought I'd throw the idea out.

**Comment by egthomas** [comment]
I just made one last, quick push to clear up some of the simpler warning messages in the binaries and a few libraries.  I now see 289 warnings in the log file after compiling this branch compared to 483 warnings on the `4.1/release` branch.

I am seeing some implicit declaration warnings in make_fit that I haven't touched:

```
make_fit.c: In function ‘main’:
make_fit.c:236:11: warning: implicit declaration of function ‘Allocate_Fit_Prm’ [-Wimplicit-function-declaration]
       if (Allocate_Fit_Prm(prm, fit_prms) == -1) {
           ^
make_fit.c:243:8: warning: implicit declaration of function ‘Copy_Fitting_Prms’ [-Wimplicit-function-declaration]
        Copy_Fitting_Prms(site,prm,raw,fit_prms);
        ^
make_fit.c:244:8: warning: implicit declaration of function ‘Fitacf’ [-Wimplicit-function-declaration]
        Fitacf(fit_prms,fit);
        ^
make_fit.c:339:5: warning: implicit declaration of function ‘FitacfFree’ [-Wimplicit-function-declaration]
     FitacfFree(fit_prms);
     ^
```

And in the fitacf_v3 library:

```
determinations.c: In function ‘new_range_array’:
determinations.c:40:31: warning: passing argument 1 of ‘realloc’ makes pointer from integer without a cast [-Wint-conversion]
     new_range_array = realloc(fit_prms->nrang, sizeof(*new_range_array));
                               ^
In file included from /jumbo/superdarn/evan/test_rst6/rst/include/superdarn/leastsquares.h:27:0,
                 from /jumbo/superdarn/evan/test_rst6/rst/include/superdarn/fit_structures.h:33,
                 from determinations.h:31,
                 from determinations.c:27:
/usr/include/stdlib.h:480:14: note: expected ‘void *’ but argument is of type ‘int’
 extern void *realloc (void *__ptr, size_t __size)
              ^
```

@kkotyk - not sure how problematic these are but thought you might want to take a look.

**Comment by kkotyk** [comment]
@egthomas Sounds good. Probably not too problematic, but I can clean them up real quick

**Comment by egthomas** [comment]
Thanks @kkotyk - looks good to me!  My final two pull requests fixed a couple of minor errors I found when trying to build the html documentation with `make.doc`.  I'm officially done making changes to this pull request and consider it ready for merging into the release branch.

**Comment by ksterne** [comment]
@egthomas, to clarify, this doesn't get rid of all of the compiler warnings?  Just some of them that you've been able to get to?

**Comment by egthomas** [comment]
That's correct. The total number of compiler warnings (on Ubuntu 16.04) have been reduced from about 480 to about 280.

**Comment by ksterne** [comment]
@kkotyk, do you have more to add to this pull request?  We should get it in ASAP to allow some stabilizing before next week.

**Comment by kkotyk** [comment]
No no more to add. You can go full steam ahead.

**Comment by ksterne** [comment]
Welp, so much to getting to get quickly.  Sorry, I got busy with other tasks and could never stop to take a look at this.  Anyways, I didn't count the number of warnings, but on a pre-installed server and a fresh install VM, this doesn't break things.  So I'll merge it in now.

**Comment by ksterne** [comment]
Sooo, I guess I should have done a bit more testing here.  I think adding this in broke some things in a related software package.  I had a question though about what's going on in:

https://github.com/SuperDARN/rst/blob/47b9d91fc7206aa4927d887c95b631ccc7362a38/codebase/superdarn/src.dlm/rposdlm.1.9/rposdlm.c#L924

Is the `IDL_SYSFUN_DEF_F_KEYWORDS` an IDL 8 thing?  As with much of anything IDL, there's not much help with consulting the Google Box.  I'll look around, but any knowledge would be helpful.

**Comment by pasha-ponomarenko** [comment]
> Is  the IDL_SYSFUN_DEF_F_KEYWORDS an IDL 8 thing?

No, it is present in IDL6.3, although I never used it... Below is the respective HELP content:


> Creating Routines that Accept Keywords 
As described in Adding System Routines, you must register your system routine before IDL will recognize it. When registering the routine, you indicate that it accepts keyword arguments in one of the following ways: 
Specifying the KEYWORDS option for the routine in the module definition file of a Dynamically Loadable Module (DLM)
 
>Setting the KEYWORDS keyword in a call to LINKIMAGE.
 
>OR-ing the constant IDL_SYSFUN_DEF_F_KEYWORDS into the flags field of the IDL_SYSFUN_DEF2 struct passed to IDL_SysRtnAdd()
Routines that accept keywords must perform keyword processing. A routine that does not allow keyword processing knows that its argc argument gives the number of positional arguments, and argv contains only those positional arguments. In contrast, a routine that accepts keywords receives an argc that gives the total number of positional and keyword arguments, and these arguments are delivered in argv mixed together in an undefined order. 
The function IDL_KWProcessByOffset() is used to process keywords and separate the positional and keyword arguments. It is passed an array of IDL_KW_PAR structures that give information about the allowed keywords and their attributes. The keyword data resulting from this process is stored in a user defined KW_RESULT structure. Finally, the IDL_KW_FREE macro is used to clean up. 
More information about these routines and structures can be found in the following sections. 
  IDL Online Help (March 01, 2006)

**Comment by ksterne** [comment]
Thanks @pasha-ponomarenko, seems like I'll need to dive head first into IDL to figure this out.

**Comment by pasha-ponomarenko** [comment]
I never wrote a DLM so that the most I can help you with...
:-(

**Comment by egthomas** [comment]
What are the warning / error messages you're getting?

**Comment by ksterne** [comment]
I think there was a bug introduced with 8e75a66 where the line I noted above was changed, but the `rposdlm.dlm` file wasn't updated at:

https://github.com/SuperDARN/rst/blob/27490d69644385f1bdc75d9c36a6176538b3e15e/codebase/superdarn/src.dlm/rposdlm.1.9/rposdlm.dlm#L12

**Comment by egthomas** [comment]
Ah yes, you're right - I forgot to add `KEYWORDS` to the end of that line when I added keyword functionality to the RadarPosGS function.

**Comment by ksterne** [comment]
You should see the commit now in #110.  Thanks for the quick help.

**Comment by egthomas** [comment]
No problem, thanks for patching that so quickly.  I don't have the ability to test it at the moment but hopefully that solved the problem.

**Pull request merged**
