### PR TITLE
Moving non-ROS usr/codebase/ binaries and libraries to codebase/

### PR DESCRIPTION
**Pull request by egthomas**
As discussed in issue #14 , this commit moves the non-ROS binaries (make_fitex.1.4 and sctnorm.1.2) and libraries (acfex.1.3 and fitacfex.1.3) from the usr/codebase directory to the corresponding directories in codebase/.  All profiles, makefiles, and build scripts have been edited to remove dependencies on the usr/ directory.  Coupled with pull request #13 (removing ROS software) this will result in one less directory (usr/) in the home rstpath which will be tracked by this repository.

### CODE REVIEW

**Comment by ksterne** [comment]
Similarly, is the test here just to make sure basic functionality is still good with this branch?

**Comment by egthomas** [comment]
Yes, the only binaries this should have modified are make_fitex (replaced by AJ's make_fitex2?) and sctnorm (not sure what this one does?).

**Comment by egthomas** [comment]
This second commit prevents a fatal error during compilation where the various make scripts try to include the $USR_LIBPATH (which has been removed) when linking to libraries.  I've run this on a local branch combined with the ros_cleanup, pkg_cleanup, and cmpfit_cleanup branches and compilation now works flawlessly.

**Comment by egthomas** [comment]
This final commit was to resolve a conflict with build.txt in the develop branch now that the ROS files/directories are deleted.

**Comment by egthomas** [comment]
This branch has now been tested and successfully compiles on Debian 8.7.1, OpenSUSE 42.2, Mint 18.1, and Ubuntu 16.04.2.  As no functionality has changed and the files have simply been moved from one directory to another, I don't see any reason why this pull request should not be merged.

**Comment by ksterne** [comment]
I'll try to get to testing out either later tonight or later this week.  Do you think you've got most things cleaned up here?

**Comment by egthomas** [comment]
Yes, this one has been ready to be merged for a while now.  Today's commit to this branch was only about tidying up the gitignore file and doesn't actually modify what will be ignored once merged.

**Comment by ksterne** [comment]
I've gotten the `usr_cleanup` branch to compile without any problem.  I did run the fitex processing on my test file and got similar issues I think as noted in #30.  But that's not from anything this branch has caused.  So going to merge this in now.

**Pull request merged**
