### PR TITLE
feature/idl_aacgminit

### PR DESCRIPTION
**Pull request by egthomas**
This pull request adds a new IDL function called "AACGMInit" which duplicates the functionality of the similarly-named C function.  AACGMInit is basically just a wrapper for AACGMLoadCoef so the user only needs to provide a year rather than the file pointer to an open AACGM coefficient file.  I've also added support for this function to the AACGM DLM library.

### CODE REVIEW

**Comment by egthomas** [comment]
Note that there is currently a bug in the C version of AACGMInit that I've fixed in a commit on the feature/grid_v2 branch.  Eventually that will be merged in a separate pull request.

**Comment by egthomas** [comment]
I intend to put together some example code for this but unfortunately our copy of IDL was recently updated to version 8.5 and I need to wait on the IT guys to re-fix a bug in the idl_export.h file before I can compile this or any branch with DLMs (hooray for user permissions).

**Comment by ksterne** [comment]
Cool...standing by then I guess.

Should the return value be included in the documentation here?  I see it's returning the value from `AACGMLoadCoef()`, but is that the coefficients or is that an exit code?

**Comment by egthomas** [comment]
The return value is meant to be the same return value as AACGMLoadCoef, which indicates the success of whether the coefficient file was successfully loaded.  This replicates the functionality of the C version of AACGMInit:

https://github.com/SuperDARN/rst/blob/develop/codebase/analysis/src.lib/aacgm/aacgm.1.15/src/aacgm.c#L80-L91

I guess it could be more explicitly stated in the documentation, although the general IDL user is never going to actually be executing the IDL code but rather the C function via the DLM.

**Comment by egthomas** [comment]
Expected output (feature/idl_aacgminit):
```
IDL> print,aacgmconvert(60.,120.,300.,olat,olon,r)
% Loaded DLM: AACCGMDLM.
           0
IDL> print,olat,olon,r
       55.477781      -167.61061       1.0000000
IDL> print,aacgminit(2010)
           0
IDL> print,aacgmconvert(60.,120.,300.,olat,olon,r)
           0
IDL> print,olat,olon,r                            
       55.867908      -166.71001       1.0000000
```

Expected output (develop):
```
IDL> print,aacgmconvert(60.,120.,300.,olat,olon,r)
% Loaded DLM: AACCGMDLM.
           0
IDL> print,olat,olon,r                            
       55.477781      -167.61061       1.0000000
IDL> file = getenv('AACGM_DAT_PREFIX')+'2010.asc' 
IDL> openr,unit,file,/get_lun,/stdio              
IDL> s = aacgmloadcoef(unit)                      
IDL> free_lun,unit
IDL> print,aacgmconvert(60.,120.,300.,olat,olon,r)
           0
IDL> print,olat,olon,r                            
       55.867908      -166.71001       1.0000000
```

**Comment by ksterne** [comment]
Cool! Thanks for the example code.  I can see the use of this in not executing all those lines to load new coeffs.   Merging now.

**Pull request merged**
