### PR TITLE
Merging `master` back into `develop`

### PR DESCRIPTION
**Pull request by ecbland**
Thanks everyone for your contributions to RST4.7 :100:  

This PR merges the `master` branch back into `develop`.

Once this PR is merged, I suggest that we take the opportunity to rename `master` to `main` (following guidelines from github and elsewhere). Please comment here if you have any concerns about renaming our default branch.

### CODE REVIEW

**Comment by ksterne** [comment]
Think the renaming is an excellent idea!

**Comment by egthomas** [comment]
> Once this PR is merged, I suggest that we take the opportunity to rename master to main (following guidelines from github and elsewhere). Please comment here if you have any concerns about renaming our default branch.

I just checked Zenodo and it shouldn't be any problem on that end (ie everything seems to be tied to releases and not branches).

**Comment by ecbland** [comment]
Ok, I have renamed the default branch to `main`. You may need to update your local environment.

**Comment by pasha-ponomarenko** [comment]
@ecbland,  I guess we need to inform the other users/developers about the name change as they may be using outdated repositories. 
I have just heard about this from Carley and Kevin K...

**Comment by ecbland** [comment]
@pasha-ponomarenko The name change should really only affect current RST developers, so I'm reluctant to announce this more widely on the user mailing list. Users should be installing the citable releases published on Zenodo for official work (or equivalently, the tagged versions on Github, e.g. `v4.7`). The `master`/`main` (and `develop`) branches often differ from the official releases and therefore there are consequences for reproducibility.

**Pull request merged**
