### PR TITLE
feature/snd library and binaries

### PR DESCRIPTION
**Pull request by egthomas**
This pull request adds C, IDL, and DLM library support and two new binaries (`make_snd` and `trim_snd`) for working with the new dmap `snd`-format frequency sounding files produced by the `interleavesound` control program, which is scheduled for a network-wide experiment early next month (September 2020).

To provide some context, at the ROS-style radars a `snd`-format file is produced on-site in real-time by the `interleavesound` control program and contains a subset of the radar parameter block and fitted parameters (eg, velocity, power, spectral width, phi0).  The `make_snd` binary is intended to support multi-channel or non-ROS style radars which cannot produced fitted parameters on-site.  Therefore, `make_snd` converts a `fitacf`-format (produced off-site from a `rawacf` file via `make_fit`) file to a `snd`-format file for more consistent data analysis.

To test the new library and binaries, you should be able to produce a `snd`-format file from any `fitacf`-format file using `make_snd`, and then use `dmapdump` to view the contents via the command line, or use the C or IDL (and/or DLM) functions to open and read the data in software.  Note that `snd` files are incompatible with the standard RST plotting routines for `fitacf`-format files.

*edit* - `snd` files can now be plotted with either `time_plot` or `field_plot` by including the new `-snd` option.

### CODE REVIEW

**Comment by ecbland** [comment]
Ok, I'm able to make a `snd` file using `make_snd`, view the contents with `dmapdump` and plot the data using `time_plot -snd` and `field_plot -snd`. 

@egthomas Has the DSWG been notified of this new data format? I don't see any need for that to hold up this PR (I know your special time is scheduled for next month), but I guess this should be put into the DSWG queue and the documentation can be written to accompany the next RST release (whenever that may be).

**Comment by egthomas** [comment]
@ecbland that's a good suggestion, thanks!  I'll open an issue / request with the DSWG about the new format (although I am also still hoping for some feedback from users on what else may be useful to include for analysis of the sounding data).

**Comment by egthomas** [comment]
Any chance of this pull request being approved before next week's Discretionary Time experiment? That might allow radar operators (or anyone else) to more easily assess the quality of sounding files collected during the experiment.

**Comment by ecbland** [comment]
@egthomas Sorry, this slipped off my radar while I was away on holiday. I did test this a few weeks ago and I think it's a good idea to merge it before your special time run begins. Of course users would still have to navigate over to the `develop` branch to use the feature.

**Pull request merged**
