### PR TITLE
Adding MLT_v2 DLM functionality

### PR DESCRIPTION
**Pull request by egthomas**
This pull request introduces DLM functionality for 3 functions from the MLT_v2 library:

1. MLTConvertYMDHMS_v2
2. MLTConvertYrsec_v2
3. MLTConvertEpoch_v2

These should fully replicate the parameters and keywords of the equivalent IDL routines while providing much faster processing time.  Comparisons can be made with Simon's online calculator located here:

http://sdnet.thayer.dartmouth.edu/aacgm/aacgm_calc.php

(note that the MLT date/time bugfix from #65 is necessary for this to function correctly)

### CODE REVIEW

**Comment by egthomas** [comment]
equally as exhaustive instructions as were provided for #67 will be available tomorrow (ran out of time today)

**Comment by egthomas** [comment]
Today's commit fixes several bugs in the error handling of input variable types in the calls to the various MLT DLMs.  Below are the test cases for the changes with and without the bugfixes from the v2-updates branch.

master branch: (no DLMs)
```
IDL> help,/dlm,'mltdlm'                       
** MLTDLM - MLTDLM (not loaded)
    Version: 1.0, Build Date: October 2010, Source: R.J.Barnes, JHU/APL
    Path: /jumbo/superdarn/evan/test_rst4/rst/dlm/mltdlm.so
IDL> year = 2017                              
IDL> yrsec = TimeYMDHMSToYrsec(2017,1,1,0,0,0)
IDL> print,MLTConvertYrsec_v2(year,yrsec,180.)

ERROR: Date and Time are not currently set.

You MUST use one of the functions below in order to set the
 date and time for the coordinate transformations, at least once.

 AACGM_v2_SetNow - use the current date and time, in UT.

 AACGM_v2_SetDateTime(year, [...]) - set date and time.

% Attempt to subscript P with <INT      (       1)> is out of range.
% Execution halted at: MLTCONVERT_V2     139 /jumbo/superdarn/evan/test_rst4/rst/idl/lib/analysis/mlt.2.0/mlt_v2.pro
%                      MLTCONVERTYRSEC_V2  288 /jumbo/superdarn/evan/test_rst4/rst/idl/lib/analysis/mlt.2.0/mlt_v2.pro
%                      $MAIN$              1 /jumbo/superdarn/evan/test_rst4/rst/idl/lib/superdarn/legacy.1.6/global.pro
IDL> aacgm_v2_setdatetime(2017,1,1,0,0,0)     
       0
IDL> year = 2017                              
IDL> yrsec = TimeYMDHMSToYrsec(2017,1,1,0,0,0)
IDL> print,MLTConvertYrsec_v2(year,yrsec,180.)
% Compiled module: FACTORIAL.
       6.7585960
IDL> years = replicate(year,10)               
IDL> yrsecs = replicate(yrsec,10)             
IDL> in_mlon = findgen(10)*360./10.
IDL> out_mlt = MLTConvertYrsec_v2(years,yrsecs,in_mlon)
IDL> for ii=0,9 do print,in_mlon[ii],out_mlt[ii]
      0.00000       18.758596
      36.0000       21.158596
      72.0000       23.558596
      108.000       1.9585960
      144.000       4.3585960
      180.000       6.7585960
      216.000       9.1585960
      252.000       11.558596
      288.000       13.958596
      324.000       16.358596
```

feature/mlt_v2_dlm branch **without** v2-updates bugfixes: (doesn't properly access AACGM date/time)
```
IDL> help,/dlm,'mltdlm'                                
** MLTDLM - MLTDLM (not loaded)
    Version: 2.0, Build Date: June 2017, Source: R.J.Barnes (JHU/APL) & E.G.Thomas (Dartmouth)
    Path: /jumbo/superdarn/evan/test_rst4/rst/dlm/mltdlm.so
IDL> year = 2017          
IDL> yrsec = TimeYMDHMSToYrsec(2017,1,1,0,0,0)                                      
IDL> print,MLTConvertYrsec_v2(year,yrsec,180.)         
% Loaded DLM: MLTDLM.

**************************************************************************
* AACGM-v2 ERROR: No Date/Time Set                                       *
*                                                                        *
* You must specifiy the date and time in order to use AACGM coordinates, *
* which depend on the internal (IGRF) magnetic field. Before calling     *
* AACGM_v2_Convert() you must set the date and time to the integer values*
* using the function:                                                    *
*                                                                        *
*   AACGM_v2_SetDateTime(year,month,day,hour,minute,second);             *
*                                                                        *
* or to the current computer time in UT using the function:              *
*                                                                        *
*   AACGM_v2_SetNow();                                                   *
*                                                                        *
* subsequent calls to AACGM_v2_Convert() will use the last date and time *
* that was set, so update to the actual date and time that is desired.   *
**************************************************************************

             NaN
```

feature/mlt_v2_dlm branch **with** v2-updates bugfixes: (now sets AACGM date/time automatically)
```
IDL> help,/dlm,'mltdlm'                       
** MLTDLM - MLTDLM (not loaded)
    Version: 2.0, Build Date: June 2017, Source: R.J.Barnes (JHU/APL) & E.G.Thomas (Dartmouth)
    Path: /jumbo/superdarn/evan/test_rst4/rst/dlm/mltdlm.so
IDL> year = 2017                                          
IDL> yrsec = TimeYMDHMSToYrsec(2017,1,1,0,0,0)
IDL> print,MLTConvertYrsec_v2(year,yrsec,180.)
% Loaded DLM: MLTDLM.
       6.7585960
IDL> years = replicate(year,10)
IDL> yrsecs = replicate(yrsec,10)
IDL> in_mlon = findgen(10)*360./10.
IDL> out_mlt = MLTConvertYrsec_v2(years,yrsecs,in_mlon)
IDL> for ii=0,9 do print,in_mlon[ii],out_mlt[ii]
      0.00000       18.758596
      36.0000       21.158596
      72.0000       23.558596
      108.000       1.9585960
      144.000       4.3585960
      180.000       6.7585960
      216.000       9.1585960
      252.000       11.558596
      288.000       13.958596
      324.000       16.358596
```

**Comment by egthomas** [comment]
I'm going to merge #65, #66, #67, and #68 next week since they've been open for nearly 2 months with no apparent testing activity (other than my own).

**Comment by sshepherd** [comment]
Agreed

**Comment by pasha-ponomarenko** [comment]
Have a question, pushy gys: is it going to be much faster now to calcualte MLT using mlt_v2.pro? Before it would take about 7 min to process one file.

**Comment by pasha-ponomarenko** [comment]
Then I migh be thinking of letting you go this time...

**Comment by sshepherd** [comment]
It certainly would be if you are using the DLMs that Evan updated.

On Tue, Jul 25, 2017 at 4:21 PM, pasha-ponomarenko <notifications@github.com

**Comment by egthomas** [comment]
I haven't done comparisons for the MLT_v2 DLM but it seems comparable in speed to the old MLT DLM.

(for AACGM_v2 there was a ~4x speed increase going from the IDL to DLM version)

**Comment by ksterne** [comment]
Same concern as #66, and #67, any need to reprocess any data based on this merged in code?

**Comment by egthomas** [comment]
No files will need to be reprocessed as a result of these merges because they either 1) only affect IDL coordinate transformations or 2) only affect the grid/map processing routines with the v2 libraries implemented which are still restricted to feature branches.

**Pull request merged**
