### PR TITLE
rtgrid cleanup

### PR DESCRIPTION
**Pull request by egthomas**
This pull request fixes several issues with the `rtgrid` binary, including AACGM_v2 and Chisham virtual height model compatibility and typos in several command line options.  Updates are also made to the appropriate documentation pages.

### CODE REVIEW

**Comment by ksterne** [comment]
I see most of this is updates to documentation, but can you provide examples to test the updates to the rtgrid code?

**Comment by egthomas** [comment]
I don't think it even works in its current state because the AACGM_v2 datetime functionality was never properly implemented (admittedly my fault).  The `intertial` command line option was fixed to be `inertial`, and previously the power and velocity min/max command line options were reversed (eg a custom maximum velocity with `-vmax` would be stored as a maximum power threshold, a minimum power with `-pmin` would be stored as a minimum velocity threshold, etc).  

For running the code, the examples at the bottom of the documentation page should still work (with a different host and port associated with a functioning real-time feed):

https://superdarn.github.io/rst/superdarn/src.bin/tk/tool/rtgrid/index.html

**Comment by egthomas** [comment]
`rtgrid` threw a couple of seg faults and core dumps yesterday during Discretionary Time on all of the Canadian radars and Kodiak, and then again today around 9 UT.  Not sure if it had something to do with the 15 km mode that was being run.  Presumably `fitacfserver` could be used in conjunction with the finalized data and `rtgrid` to replicate the conditions which caused the core dumps if one was feeling ambitious.

**Comment by egthomas** [comment]
Another fun bug - after running for nearly 2 weeks, the Hokkaido West real-time grid files are now being stored under the `tst` 3-letter code (eg `20181022.tst.grdmap` and `grid.rttst.grdmap`).  `dmapdump` shows that some of the files have recorded a stid of 0, while others have recorded the correct stid of 41.  This could turn particularly nasty if multiple radars have their stid corrupted within their `rtgrid` process and they start overwriting one another's real-time grid files.  Best of luck to whatever poor soul who may try fixing this in the future.

**Comment by kkotyk** [comment]
I've also had major issues with realtime code. Records get corrupted all the time and cause issues, so I wouldn't be surprised if datamapdecodebuffer segfaults in other places eventually. My main motivation for writing a Python version of dmap was actually to be able to create more robust and useful web backends using spotty data. This may be slightly off topic from the original PR but I would suggest writing a small proxy utility that connects to the radars, runs the record through the Python dmap to error check it, and if it succeeds just forward that data to the rst realtime utilities. That should keep your backend alive without any segfaults and I think should be a very small and simple python script.

**Comment by egthomas** [comment]
@kkotyk thanks for the response.  That sounds like a good project for a student - and maybe something that could be included in pydarn?

**Comment by mts299** [comment]
Pydarn has a python dmap file that includes error checking now. 
What concerns me is why do we not gracefully handle these "errors" in the stream within the RST RT utilities?

**Comment by kkotyk** [comment]
Very doable for a student. I'm not sure how it would fit into the scheme of pydarn, but as pydarn evolves it would be nice to have a collection of helpful utilities that people create.

**Comment by kkotyk** [comment]
@mts299 Cause the same dmap stuff that is used to read files is also used for realtime decoding. So if something fails there its not really the fault of the RT utils.

**Comment by mts299** [comment]
@kkotyk actually it has already been planned into the schema for Pydarn. 

Should we not look into dmap in RST for better error handling (future PR)?

**Comment by kkotyk** [comment]
@mts299 I would agree, however this discussion has happened before and landed at impasse with strong opinions on either side about whether to add error checking. Without a firm decision from the DAWG chair or PIs, I personally have decided to not pursue that avenue for now.

**Comment by egthomas** [comment]
@mts299 anything I can do to help with testing this pull request?

**Comment by mts299** [comment]
@egthomas No, I just haven't gotten around to it. I was going to finish 209 first then maybe this one and the Codacy one. 

If there is any step by step guide for testing this PR then that might speed things on my end.

**Comment by egthomas** [comment]
These most recent commits address the `warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]` messages raised by gcc for various binaries by cleaning up the spacing in the source code.

**Comment by egthomas** [comment]
Is there anything that can be done to help with testing / approval of this branch?  I fully appreciate that it is more difficult to test than most other changes because of the focus on real-time data streams.

If it counts for anything, we've been using this branch for >9 months to perform continuous real-time gridding of data streams from 15+ radars.

**Comment by mts299** [comment]
Sorry, @kkotyk and I have been very busy with other projects, and with the latest push back on RST my interests in helping have fallen short, and other projects took over priority.

As discussed in the DAWG working group meet and the SuperDARN conference room, cowboy coding (self-pushing code) was strongly discouraged as it does not emulate the user-reproducibility factor. So I strongly disagree on pushing your own code even though you have been using it for 9 months this doesn't handle the use case.   

I think this PR would be a good case of posting testing code and what to expect or look for as @ksterne asked a while back. 

Summary of probably what you want to do for testing: 
`rtgrid -L log -tl 120 -i 120 -if pid.id kapqnx.jhuapl.edu 1024`
Generate a grdmap file using the real-time data stream from the host "kapqnx.jhuapl.edu", served at port 1024. Ignore the scan flag and use a scan length of two minutes. Generate a record every two minutes. The process identifier is recorded in the file "pid.id", logs of all transactions are recorded in the file "log.yyyymmdd" where yyyy is the year, mm is the month, and dd is the day.

https://superdarn.github.io/rst/superdarn/src.bin/tk/tool/rtgrid/index.html

This above example was all taken from the documentation link above. My assumption on testing is to make sure no errors are produced, the reasonable grid map file is created that you could plot using this command 

`grid_plot -png -dn -mag -rotate -fcoast -coast -fterm -tmk -vecp -vkeyp -time -raw 20021219.grdmap > rtgrid_test.png`

segfaults or crashes do not occur and runs for a certain amount of time.

**Comment by egthomas** [comment]
> Sorry, @kkotyk and I have been very busy with other projects, and with the latest push back on RST my interests in helping have fallen short, and other projects took over priority.

Not a problem, my question was not addressed to anyone in particular since I appreciate that participation in this WG is a volunteer effort.

> As discussed in the DAWG working group meet and the SuperDARN conference room, cowboy coding (self-pushing code) was strongly discouraged as it does not emulate the user-reproducibility factor. So I strongly disagree on pushing your own code even though you have been using it for 9 months this doesn't handle the use case.

I apologize if it came across that way, but I was not trying to imply this pull request was in any danger of being self-pushed.

> I think this PR would be a good case of posting testing code and what to expect or look for as @ksterne asked a while back.

Yes, the `rtgrid` example is taken from the documentation which I originally provided @ksterne a link to in September.  Note that the host and port need to be changed, as data from that radar is no longer being served by APL.

**Comment by mts299** [comment]
@egthomas would you be able to give a command that has updated option value in it maybe even the type of command you would use to plot it to make sure it is working?

**Comment by mts299** [comment]
@egthomas I noticed a typo in the documentation: 
```
rtgrid -rpf port.gbr -L log -pf port.id -if pid.id -p /data/rt/grd gbayqnx.jhuapl.edu
```

I think you mean:
```
rtgrid -rpf port.gbr -L log -if pid.id -p /data/rt/grd gbayqnx.jhuapl.edu
```

There is no `pf` option. 

Currently testing it with inuvik, so far working.

**Comment by mts299** [comment]
@egthomas is this normal:
**************************************************************************
* AACGM-v2 ERROR: No Date/Time Set                                       *
*                                                                        *
* You must specifiy the date and time in order to use AACGM coordinates, *
* which depend on the internal (IGRF) magnetic field. Before calling     *
* AACGM_v2_Convert() you must set the date and time to the integer values*
* using the function:                                                    *
*                                                                        *
*   AACGM_v2_SetDateTime(year,month,day,hour,minute,second);             *
*                                                                        *
* or to the current computer time in UT using the function:              *
*                                                                        *
*   AACGM_v2_SetNow();                                                   *
*                                                                        *
* subsequent calls to AACGM_v2_Convert() will use the last date and time *
* that was set, so update to the actual date and time that is desired.   *
*************************************************************************

I did get a segfault after that message.

**Comment by mts299** [comment]
NVM I think I was using an old `rtgrid`, recompiled from the branch and seems to be working now with Clyde and Inuvik.

**Comment by mts299** [comment]
Seems to be working now, here a plot I made from the command: 
`grid_plot -png -dn -mag -rotate -fcoast -coast -fterm -tmk -vecp -vkeyp -time -raw  20190719.cly.grdmap`



I will let it run over the weekend, and if there is no segfaults then we can merge it on Monday :+1:

**Comment by mts299** [comment]
No crashes over the weekend and grid maps look good. 

Merging in the code!

**Pull request merged**
