### PR TITLE
Release 4.0

### PR DESCRIPTION
**Pull request by egthomas**
As described in #54, we have decided to adopt the approach of renaming the original `master` branch to `master-old` and will create a new `master` branch from this `release-4.0` branch once the testing period is complete.  

This pull request to merge the `release-4.0` branch back into `develop` - which will occur simultaneously with the creation of the new `master` branch upon completion of testing - will help us track any additional changes on the `release-4.0` branch.

### CODE REVIEW

**Comment by egthomas** [comment]
So, we're about a week away from the scheduled 4.0 release.  Does anyone have any comments, thoughts, suggestions, etc?  Any last bugs or compilation quirks we should address?

**Comment by sshepherd** [comment]
Release it.

**Comment by aburrell** [comment]
I’ve just tested the compilation on a mac and made some fixes.  I’ll push them today.

**Comment by ksterne** [comment]
Sounds good here. I still thinking holding off until the 31st is good as we're seeing a few other ones come in (#61, #62).  One question, do you want to handle that or would you like me to handle it?

**Comment by pasha-ponomarenko** [comment]
Just a generatl question: could renaming cause problems with future roll-backs?

**Comment by pasha-ponomarenko** [comment]
Sorry, pushing the wrong button!

**Comment by egthomas** [comment]
@ksterne - we all probably need to iterate on the text for the description of the v4.0 release tag since there have been a lot of changes post-VTRST3.5 (200+ commits?) and it may take some effort to summarize them.

@pasha-ponomarenko - do you mean renaming `master` to `master-old` might cause problems?  I don't think so, since I can't see why we would want to ever roll back to the `master`/`master-old` branch as it is so woefully out of date.

**Comment by ksterne** [comment]
@egthomas, as a start on release notes:

- This is a distinct break away from the VTRST3.5 repository and will be actively developed and maintained by the Data Analysis Working Group of SuperDARN.
- This release removes most, if not all, code associated with radar operations that were introduced in the early 3.x versions of the code package.

From there, I guess it's worth putting in notes on the couple of non-removal pull requests that were made.  I'm guessing this is mostly Simon's update/addition of coefficients?  Maybe there's a few others to review there.  Again, do you want me to handle the new release creation or would you like to?  I can at least make the branches and the release point, but you/we can always go back later to edit the release notes on the release...I think.

**Comment by egthomas** [comment]
Thanks @ksterne, those look good.  I'll go through the commits tonight/tomorrow and see what else should be added.  It may be easier for me to do since I've got admin privileges to switch around the current default branch.

**Comment by ksterne** [comment]
Woohoo! Everything looks good with the new release and then merging this back into develop!  Great job everyone!

**Comment by pasha-ponomarenko** [comment]
Well done, guys!
I missed the event -- it was 6:47AM here... 
Where can I see the final statistics so that I can mention it in the WG report?

**Comment by egthomas** [comment]
@pasha-ponomarenko - Not sure what kind of statistics you're looking for, but here are some rough numbers from when this repository was started in November 2016 (and broke away from the VTRST).

- 154 commits
- 35 pull requests approved
- 115,721 additions (ie lines)
- 4,071,847 deletions (ie lines)
- 5 contributors (doesn't include testers or approvers of pull requests)

**Comment by pasha-ponomarenko** [comment]
Thanks, Evan! that's what I need.

Pasha

Sent from my Sony Xperia™ smartphone

---- Evan Thomas wrote ----


@pasha-ponomarenko<https://github.com/pasha-ponomarenko> - Not sure what kind of statistics you're looking for, but here are some rough numbers from when this repository was started in November 2016 (and broke away from the VTRST).

  *   154 commits
  *   35 pull requests approved
  *   115,721 additions (ie lines)
  *   4,071,847 deletions (ie lines)
  *   5 contributors (doesn't include testers or approvers of pull requests)

**Comment by pasha-ponomarenko** [comment]
Guys, I would like to commend your effort on refactoring RST, now on a very personal note: 
being a total Linux dummy, I still was able to install RST4.0 on my machine and to compile it almost seamlessy (had to read the istructions carefully!). 
The dream came true!
:-)

**Pull request merged**
