### PR TITLE
4.2 release

### PR DESCRIPTION
**Pull request by ksterne**
This is the pull request for the 4.2 release as called for in #174 and after the acceptance of the RST release guidelines by the SuperDARN DAWG.  If I was in the lab, I'd be able to make better notes about all of the pull requests here or make some highlights, but in the interest of time I'm getting this going.  Maybe we can collect that here or start to summarize for the release notes.

I would encourage all devs to test on this branch exclusively to try to find any additional bugs.  This pull request should be merged on/by August 24th.  I mention this date as I won't be able to do any testing in the coming week as I'm out of the lab.  Does anyone want to volunteer to merge it when the time comes?

@egthomas, I'm guessing one commit we'll be expecting here modifies the `--version` output as @mts299 mentioned in #173?

Is there anything else that we should look at before merging this to master?

### CODE REVIEW

**Comment by ksterne** [comment]
I assigned @egthomas, @mts299 as they might be the quickest to address the version number issue.

**Comment by asreimer** [comment]
I made the change to the version number.

I can confirm that I'm able to install `4.2-release` on Fedora 28 and I'm able to run `solve_model` and `make_fit` fine. Also `test_aacgm` spits out what it should.

I noticed that `solve_model` is missing the `--version` option, so I've added it. If I'm not supposed to do that in this branch, revert and I'll submit a new pull request.

What's the timeline like on this besides ASAP? End of next week? I'm working on a testing script, but ran out of time tonight.

**Comment by ksterne** [comment]
The guidelines note no more than 2 weeks of testing for this.  I personally would like to have close to that full two weeks since I won't be able to test over the next week as I'm at the Kapuskasing radar.  I actually have tested any of the new commits to `develop` from roughly the last month or so on our main system at VT.  So, that's why I noted: 

> This pull request should be merged on/by August 24th. 

Looks like there's some issues with the travis CI build checking.  I think it's more on the dependencies than our code.  On the initial pull request yesterday is was failing on the netcdf package, but now it seems to be failing on the `libhdf5-serial-dev` package. Both of these look like it's a timeout on connecting to download the package, so possible it's an external issue that we don't need to worry about?

**Comment by asreimer** [comment]
>  @ksterne: So, that's why I noted:

Ugh, sorry. Thanks for repeating that.

The build failed because Ubuntu repos were unreachable. That seems to have resolved itself.

**Comment by pasha-ponomarenko** [comment]
I am away until Tuesday, but i should be able to check emails on my mobile. Do we have a draft of the release summary somewhere?

**Comment by mts299** [comment]
For map_plot, the documentation shows -stereo but says it is not recognized when you run the command.

**Comment by ksterne** [comment]
Looks like that's a disconnect in the documentation as I don't see it listed out in the available options from `map_plot --help`, but it is mentioned in the [Examples section of the documentation](https://superdarn.github.io/rst/superdarn/src.bin/tk/plot/map_plot/index.html).  Is this enough to hold up the release here or is this a fix for something for release 4.2.1 or 4.3?

Since it's not breaking compilation and not apparently giving bad data/values, I'm thinking it's a fix for after this release as we should only apply bugfixes here.  Others thoughts?

**Comment by mts299** [comment]
Found another cute bug: 
`map_plot  -ps -st 10:04 -et 10:10 -mag -rotate -hmb -modn -fit -grd -ctr  -imf -dn -extra -coast -vecp  -pot -time -vkeyp -vkey rainbow.key -path 20180411.map`
11-4-2018 18:1:53
Maybe if the start time does not match the file start time we should throw an error, or warning? especially if an end time is set. This can seem confusing. I later realized that my files all started at 18:00 

Sorry, I probably should have caught that in plot fixes PR. This could be fixed for 4.3 as well as it may be an issue in other plotting tools.

**Comment by mts299** [comment]
> hold up the release here or is this a fix 

How long of a hold up is this? seems like a quick fix.

**Comment by ksterne** [comment]
I've got a draft release typed up.  If anyone's online and wants to give it a quick look, go ahead and let me know.  I'll be merging this within the hour (hopefully).

**Comment by egthomas** [comment]
@ksterne I must have been working on it at the same time as you: 
 https://github.com/SuperDARN/rst/releases/tag/untagged-9f7c6801a503cd2b0115

Note that the html documentation requires manual updating and lives on the `gh-pages` branch, so it won't reflect any changes to `develop` or `master` (or any other branch) in real time.  I pushed the changes earlier today so it should now match the documentation on the 4.2 release branch.

**Comment by ksterne** [comment]
Whoops, OK @egthomas, I'll go with yours as default here since I think yours looks a little better.  I do have a few lines I'll pull from mine into yours though.

I'm not as up on the html documentation here, maybe next time we're talking you can give me the short on that.

**Comment by egthomas** [comment]
Ok no problem.  I think this is safe to merge then.  Do you want to go ahead and do the merge from `master` back to `develop` as well?

**Comment by ksterne** [comment]
Yep, that's the standard.  I'll do that process now.  @sshepherd, you can now let people know your bugfixes are released! (Though they could have grabbed them if they really wanted to.)

**Comment by pasha-ponomarenko** [comment]
Thanks a lot, guys!

**Pull request merged**
