### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by aburrell**
Updated installation instructions for mac, making it possible to avoid
all warnings during installation.

### CODE REVIEW

**Comment by aburrell** [comment]
Address issue #77 .  Test installation (basically using xterm instead of term) should remove all of the warning issues encountered previously.

**Comment by egthomas** [comment]
I think we need to change the opening line of the install notes from "Upon cloning the repository" to something like "Upon obtaining the software".  A lot of users will be installing from the zip/tar archive and won't know what "cloning" refers to.

**Comment by egthomas** [comment]
Also, are steps 4a and/or 4b necessary with the other updated instructions?

**Comment by aburrell** [comment]
I thought it would be helpful to keep them for people who may not want to use/install an xterm client, since once rst is installed it works fine in the default terminal application.

**Comment by egthomas** [comment]
Piggybacking on this pull request to update the documentation in the README.txt file which describes the make.build / make.code / make.doc scripts.  Also deleted two unnecessary lines from the build.txt file.  I can break these out into a separate pull request if desired but it seemed like this might be an acceptable place to update other readme info.

**Comment by egthomas** [comment]
Just made one more commit generalizing the first installation step and removing the tilde's from the example rst/ paths.  Not sure if I'm allowed to merge this but I think someone should go ahead and do so.

**Comment by aburrell** [comment]
The changes look good.  I think it's better that you merge it than I, given that I started the pull request.

**Comment by egthomas** [comment]
Don't need to ask twice!

**Pull request merged**
