### PR TITLE
AACGM_v2 update

### PR DESCRIPTION
**Pull request by egthomas**
This pull request updates the AACGM_v2 coefficients and source code based on @sshepherd's recently released v2.6 of his AACGM_v2 software.  The main improvement is the utilization of the new IGRF13 model coefficients which extends the temporal coverage by 5 years from 2020 to 2025, as well as a few other bug fixes made by @sshepherd.  Note that without these changes, AACGM_v2 coordinate transformations for dates on or after 1st January 2020 (ie tomorrow) will be impossible.

I've fixed a few other typos and environment variables necessary for compilation, and also generated older-style igrf/dgrf coefficient files needed by the IGRFCall function used by the gridding software.  

Any questions or complaints can be directed to @sshepherd.  Happy new year!

### CODE REVIEW

**Comment by ecbland** [comment]
Thanks @egthomas !
Any instructions on how to test this, or should we just check that it works with some 2020 data? I can test this on Monday

**Comment by egthomas** [comment]
@ecbland You can also use the `test_aacgm` binary written by @sshepherd, although it looks like its output can no longer be compared to the `expected.txt` file in that same directory.  Maybe that file should be removed?

**Comment by ecbland** [comment]
Tested by creating grid files for some 2020 data and everything seems to work. The IDL code for AACGM_v2 works too. 

Yes, I think `expected.txt` should be removed from the `aacgm_test` directory. 

@ksterne This update is required to create grid/map files for 2020 data, so perhaps a patch release is appropriate after it is merged?

**Comment by egthomas** [comment]
@ecbland the `expected.txt` file has been removed, and I agree that approval of this pull request warrants at least a new patch release (if not a minor release, since this goes beyond a simple bug fix).

**Comment by ksterne** [comment]
I might sound like a broken record, but sorry I've been absent from some here.  I'm hoping to put together an initial thought on a release "project" tomorrow.  I agree we should try to get this out ASAP even though it's hard to make complete map data without solar wind info and all of the radar data.

**Comment by ksterne** [comment]
Whoops, I saw @ecbland had a release project already started up for the next minor release.  I've added some there and looked through some older parts.

Anyways, back to this, @sshepherd (or @egthomas) I had a read through the release notes and didn't see anything about this, but does this updated code modify any results prior to Jan. 1, 2020?  I'm wondering what the impact might be to previously generated data.

**Comment by egthomas** [comment]
From @sshepherd's announcement in the SPA newsletter:

> Note that small differences in the IGRF-13 coefficients will cause corresponding small changes in AACGM-v2 coordinates derived using the new model for dates beginning in 2010.

**Comment by ksterne** [comment]
This pull request is being elevated to a patch release do to the urgency on needing to release this code that was not apparent at first.  I've cherry-picked the commits into the `4.3.1-release` branch.  This will cause some merge conflicts when we make a 4.4 release and merge that into `master`, but it seems as though there's no *good* way around that.

**Pull request merged**
