### PR TITLE
Remove thresholding in rawwrite and oldrawwrite libraries

### PR DESCRIPTION
**Pull request by egthomas**
This pull request addresses issue #142 by disabling the thresholding in the rawwrite and oldrawwrite libraries (in both C and IDL).  You can test that `dattorawacf` and `rawacftodat` now both reproduce the original file by default using the following tests:

```
dattorawacf 2005123120t.dat > 2005123120t.rawacf
rawacftodat 2005123120t.rawacf > 2005123120t.dat2
cmpraw 2005123120t.dat 2005123120t.dat2 > diff_dat.txt
```

```
make_fit -old 2005123120t.dat 2005123120t.fit
dattorawacf 2005123120t.dat > 2005123120t.rawacf
rawacftodat 2005123120t.rawacf > 2005123120t.dat2
make_fit -old 2005123120t.dat2 2005123120t.fit2
cmpfit 2005123120t.fit 2005123120t.fit2 > diff_fit.txt
```

Feel free to substitute the example dat file for whichever date/radar you prefer (although  note that pull request #139 is necessary to avoid seg faults when converting early (pre-1996) dat files).

### CODE REVIEW

**Comment by kkotyk** [comment]
I tested with 2005021512k.dat and this works as you say it should, however using 2005021516e.dat I get a segfault when converting the rawacf back to dat. Is this also part of the #139 issue?

**Comment by egthomas** [comment]
No, I think that's because the `combf` field is empty for at least some of the records in the `2005021512k.dat` file, causing the `strcpy(oldraw.COMBF,prm->combf);` line in OldRawWrite to throw the seg fault.

**Comment by kkotyk** [comment]
Okay, so an issue for a different PR then?

**Comment by egthomas** [comment]
Well I went ahead and fixed it in commits abc23ff and 8626790 on this pull request.  I don't know of any other files off the top of my head which also have those empty combf strings.

**Comment by mts299** [comment]
With the cmpfit and cmpdat are we looking for a lot of output or none? 

Also does the combf check just exit if it is zero? I noticed 2005021516e.fit2 was fairly small in size but I did not get any segfaults. 

Here is what I got for file sizes: 
 ls -la *.dat2 *.dat
-rw-r--r-- 1 marina users 19307711 Aug  3 11:07 2005021514f.dat
-rw-r--r-- 1 marina users 20690000 Aug  3 11:15 2005021514f.dat2
-rw-r--r-- 1 marina users 19598239 Aug  3 11:06 2005021516e.dat
-rw-r--r-- 1 marina users 20690000 Aug  3 11:17 2005021516e.dat2
-rw-r--r-- 1 marina users  8327529 Aug  3 11:06 2005021520t.dat
-rw-r--r-- 1 marina users 10345040 Aug  3 11:17 2005021520t.dat2
 ls -la *.fit2 *.fit
-rw-r--r-- 1 marina users 9675776 Aug  3 11:13 2005021514f.fit
-rw-r--r-- 1 marina users 9675776 Aug  3 11:16 2005021514f.fit2
-rw-r--r-- 1 marina users 9147392 Aug  3 11:13 2005021516e.fit
-rw-r--r-- 1 marina users     833 Aug  3 11:18 2005021516e.fit2
-rw-r--r-- 1 marina users 3298304 Aug  3 11:13 2005021520t.fit
-rw-r--r-- 1 marina users     833 Aug  3 11:22 2005021520t.fit2

**Comment by egthomas** [comment]
If the output raw or fit files truly are the same then they should show something like

```
2005-02-15 16:02:00	2005-02-15 16:02:00
2005-02-15 16:02:00	2005-02-15 16:02:00
2005-02-15 16:02:07	2005-02-15 16:02:07
2005-02-15 16:02:07	2005-02-15 16:02:07
2005-02-15 16:02:15	2005-02-15 16:02:15
2005-02-15 16:02:15	2005-02-15 16:02:15
2005-02-15 16:02:22	2005-02-15 16:02:22
2005-02-15 16:02:22	2005-02-15 16:02:22
2005-02-15 16:02:29	2005-02-15 16:02:29
2005-02-15 16:02:29	2005-02-15 16:02:29
2005-02-15 16:02:36	2005-02-15 16:02:36
2005-02-15 16:02:36	2005-02-15 16:02:36
2005-02-15 16:02:44	2005-02-15 16:02:44
```

The `combf` check won't exit if it finds an empty string, it just leaves the string empty in the new file's parameter block and continues with the conversion (instead of seg faulting).  Not sure why your second fit file was smaller...

**Comment by egthomas** [comment]
Any more progress testing this @mts299 / @kkotyk ?

**Comment by mts299** [comment]
@egthomas Sorry for leaving we had a long weekend here. I will give it another test run today.

**Comment by mts299** [comment]
Sorry was going to make a comment and then hit the wrong button

**Comment by mts299** [comment]
Tests I did: 
For 2005021514f.dat I get they are the same when compared for both the dat and the fit test. However, the file size is still different for the dat files:
-rw-r--r-- 1 marina users 19307711 Aug  3 11:07 2005021514f.dat
-rw-r--r-- 1 marina users 20690000 Aug  7 10:40 2005021514f.dat1
-rw-r--r-- 1 marina users 20690000 Aug  7 10:46 2005021514f.dat2

ls -la 2005021514f.fit*
-rw-r--r-- 1 marina users 9675776 Aug  7 10:44 2005021514f.fit
-rw-r--r-- 1 marina users 9675776 Aug  7 10:46 2005021514f.fit2

For 2005021516e.dat I get the same for both tests... weird how last time I didn't maybe I didn't pull, or I missed typed something. Again the file size is different but it seems there is just some type of buffering going on when we convert to a dat file: 
ls -l 2005021516e.dat* 2005021516e.fit*
-rw-r--r-- 1 marina users 19598239 Aug  3 11:06 2005021516e.dat
-rw-r--r-- 1 marina users 20690000 Aug  7 10:50 2005021516e.dat1
-rw-r--r-- 1 marina users 20690000 Aug  7 10:53 2005021516e.dat2
-rw-r--r-- 1 marina users  9147392 Aug  7 10:52 2005021516e.fit
-rw-r--r-- 1 marina users  9147392 Aug  7 10:54 2005021516e.fit2

Again this passed both dates however, the file size is a bit different. 
ls -l 2005021520t.dat* 2005021520t.fit*
-rw-r--r-- 1 marina users  8327529 Aug  3 11:06 2005021520t.dat
-rw-r--r-- 1 marina users 10345040 Aug  7 10:57 2005021520t.dat1
-rw-r--r-- 1 marina users 10345040 Aug  3 11:17 2005021520t.dat2
-rw-r--r-- 1 marina users  3298304 Aug  7 10:58 2005021520t.fit
-rw-r--r-- 1 marina users  3298304 Aug  7 10:59 2005021520t.fit2

If the file sizes are not a problem then I think this PR is good to be merged.

**Comment by egthomas** [comment]
@mts299 I think the different file sizes are ok because the origin times or comment buffer strings are possibly different between them.

**Comment by mts299** [comment]
Okay, I thought there might be some buffering going on.

**Comment by pasha-ponomarenko** [comment]
@mts299, how large is the difference?

**Pull request merged**
