### PR TITLE
V2 (AACGM, IGRF, MLT) Library Updates and Bug fix

### PR DESCRIPTION
**Pull request by sshepherd**
Reformatting of V2 libraries (replacing tabs with spaces)
A small bug fix to AACGM_v2_SetNow().

### CODE REVIEW

**Comment by egthomas** [comment]
oops @sshepherd - you forgot to switch the 'base' from master to develop

**Comment by sshepherd** [comment]
Which I'm pretty sure is what you warned me about...

**Comment by egthomas** [comment]
I know someone else is supposed to test this too, but the bug fixes to AACGM_v2_SetNow() and the MLT_v2 date/time logic have corrected the errors I found while working on the DLMs.

**Comment by ksterne** [comment]
@sshepherd, @egthomas, any helping example code to test this out?

**Comment by sshepherd** [comment]
I honestly have no idea... I'm not at a computer so I can't check and it
was quite awhile ago...

**Comment by egthomas** [comment]
The only functionality changes here were motivated by #67 and #68 - try those branches without the changes from this branch and each of those will fail.  Use the fixes from this branch, and one / both of them will then work correctly.

**Comment by egthomas** [comment]
In case anyone was about to approve this (ha ha ha...), please hold off for the moment; I think there is a bug in the way the times are handled in MLT-v2 that I need to run by Simon.

**Comment by egthomas** [comment]
The most recent commit today has fixed the issue I identified last week and has been successfully tested on tens of thousands of MLT conversions for a variety of dates.  Since this pull request has been sitting here for nearly 6 weeks with no apparent action, I'm going to go ahead and merge it tomorrow.

**Comment by ksterne** [comment]
Hey @egthomas, I was going to look at this today but was holding off from your comment.  Give me a little bit and I can test this out.  I don't know that I see how to test the bugfixes right away.  Some example code and expected results will help speed things along here.

**Comment by ksterne** [comment]
@egthomas, @sshepherd, any example code to try to test this out?

**Comment by sshepherd** [comment]
Same reply as was given to your identical question 19 days ago...
Evan has some comments (above) that are more useful.

**Comment by ksterne** [comment]
So, I guess the test is to use the `feature/aacgm_v2_dlm` and `feature/mlt_v2_dlm` branches and cherry-pick the commits present in this pull request?

**Comment by egthomas** [comment]
You don't need to cherry pick commits - just doing a `git pull origin v2-updates` when you're on either of those branches is sufficient.  I've laid out detailed examples and test cases to demonstrate the functionality of the `feature/aacgm_v2_dlm` and `feature/mlt_v2_dlm` branches and also shown where they fail and how  merging this branch fixes the errors.

**Comment by ksterne** [comment]
Oh, and this one as well; sny need to reprocess data based on this code?

**Pull request merged**
