### PR TITLE
[FIX] grid_plot set delay 0 

### PR DESCRIPTION
**Pull request by mts299**
# Scope

Changed delay = 0.1 to delay = 0 to address issue #393 
The new changesets the default to allow the user to click through images when using the `-x` with `grid_plot`

## Test
`grid_plot -x -raw -mag -time -coast -fcoast 20150301.2001.00.inv.grid`

Should be able to click through the images

### CODE REVIEW

**Comment by ecbland** [comment]
@mts299 I know this is scope creep in relation to the original issue (#393), but I think the default value of `delay` should be the same for all routines that have it:

- `iqplot`
- `field_plot`
- `grid_plot`
- `map_plot`

This PR changes the default behaviour, so would it make sense to print some basic instructions in the command line? 
e.g. `Click to view next plot. Ctrl+c to exit. Use -delay option to cycle through all frames sequentially.`

**Comment by mts299** [comment]
Update:
- [x] update the other plotting methods @ecbland mentioned 
- [x] add user comment "Click to view next plot. Ctrl+c to exit. Use -delay option to cycle through all frames sequentially."
- [x] add the default in XML files as well

**Comment by ecbland** [comment]
Ok, there was some discussion off-github a while ago about whether to make this particular change. Thanks to everyone who has offered their view. This is a time where I think an executive decision is needed so that we can move forward and focus our energy on other things. Let's implement the change, and if users don't like it we can change it back in a later release. 

This decision is based on the following: 

- The current default behaviour is confusing when the user wants to view the data from a single time interval rather than a sequence of plots. Although the solution (set `-delay 0`) is in the documentation, it's still not particularly obvious to the general RST user. 
- The current default on `develop` (`-delay 0.1`) is quite fast, so most users will probably want to change it to something else anyway
- This PR modifies the default behaviour of the code, but all functionality is retained. Users can view a movie by setting `-delay` to any non-zero value

@mts299 The code works as described. There are some conflicts relating to the license text, so I will resolve those now and then merge. Thanks for your patience with this PR :+1:

**Comment by pasha-ponomarenko** [comment]
@ecbland, I am still learning how to use GitHub and just curious if "`Merge branch 'develop' into fix/grid_plot_display`" is the right way to go...

**Comment by ecbland** [comment]
> @pasha-ponomarenko I am still learning how to use GitHub and just curious if "Merge branch 'develop' into fix/grid_plot_display" is the right way to go

Yes, this is correct. This is the commit message that Github uses when resolving conflicts. Nothing to worry about.

**Comment by ecbland** [comment]
Sorry for all the extra commits -- the license notices were outdated and I should have merged them from `develop` first. Anyway, it's fixed now so I will merge this in.

**Pull request merged**
