### PR TITLE
Update mlt_v2.pro

### PR DESCRIPTION
**Pull request by mtwalach**
Correcting some typos in the comments. This has no effect on the functionality of the program.

### CODE REVIEW

**Comment by pasha-ponomarenko** [comment]
Seems harmless enough!
;-)

**Comment by ksterne** [comment]
Should this have gone into `develop` and not `master`?

**Comment by pasha-ponomarenko** [comment]
Opps! How can we revert this then?

**Comment by ksterne** [comment]
Crtl + F (or your browsers find function) 'revert' will lead you to the answer I think.

Just wondering that this didn't seem critical enough to warrant a hotfix directly into master.

**Comment by mtwalach** [comment]
Sorry - I think this happened because I originally forked from the master branch.

**Comment by mtwalach** [comment]
Okay, I pressed the revert button, but I think someone else has to merge the "reversion".

**Pull request merged**
