### PR TITLE
IDL cleanup

### PR DESCRIPTION
**Pull request by egthomas**
This pull request addresses some of the issues raised by @mtwalach in #127.  No functionality of the IDL software has been changed.

### CODE REVIEW

**Comment by pasha-ponomarenko** [comment]
@egthomas, what sort of checks besides RST installablilty would these changes require?

**Comment by egthomas** [comment]
@pasha-ponomarenko - none really since I've only modified a few comment(ed out) lines.

**Comment by egthomas** [comment]
@mtwalach - any other changes you think should be added here?

**Comment by mtwalach** [comment]
I don't use all of that stuff, so I don't know for sure but it looks fine - What are the first 4 lines in [codebase/superdarn/src.idl/startup/startup.pro](https://github.com/SuperDARN/rst/blob/master/codebase/superdarn/src.idl/startup/startup.pro) for? It looks to me like they can go as well.

**Pull request merged**
