### PR TITLE
Fixing AACGM_v2 bugs and adding pre-1900 coefficients

### PR DESCRIPTION
**Pull request by egthomas**
This pull request contains one final set of bug fixes for IDL/DLM compatibility in the AACGM-v2 software that was missed in #149.

### CODE REVIEW

**Comment by egthomas** [comment]
I believe this is mostly working except for the `/trace` keyword which is not giving the expected results.  Using the DLMs from within IDL:

```
IDL> print,aacgm_v2_setdatetime(2018,08,01,00,00,00)     
% Loaded DLM: AACGMDLM.
           0
IDL> pos=cnvcoord_v2(60.,120.,300.)                      
IDL> print,pos
       55.955571      -166.05710       1.0456635
IDL> pos=cnvcoord_v2(60.,120.,300.,/trace)
IDL> print,pos
       22.449229       179.36041       1.0456635
```
And this is using the native IDL code:

```
IDL> print,aacgm_v2_setdatetime(2018,08,01,00,00,00)     
       0
IDL> pos=cnvcoord_v2(60.,120.,300.)                 
% Compiled module: FACTORIAL.
IDL> print,pos
       55.955571      -166.05710       1.0456635
IDL> pos=cnvcoord_v2(60.,120.,300.,/trace)          
IDL> print,pos
       12.062125      -170.09346       1.0456635
```

From the online calculator (http://sdnet.thayer.dartmouth.edu/aacgm/aacgm_calc.php#AACGM):

```
FIELD-LINE TRACING

DATE    : 20180801
 0000 UT
Altitude:  290.931 km**

       Geographic                  AACGM-v2 
 Latitude     Longitude     Latitude     Longitude     MLT
(degrees N)  (degrees E)   (degrees N)  (degrees E)  (hours)
-----------  -----------   -----------  -----------  -------
  60.0000     120.0000       55.7656    -166.5262     8.0929
```

I've also modified the behavior of the `AACGM_v2_GetDateTime` function in the DLMs to suppress the warning output when the `/silent` keyword is passed to match the behavior of the native IDL function.

**Comment by sshepherd** [comment]
Is this a new change? I want to be sure that the standalone version is the
master and the RST is kept synchronized, otherwise changes in the RST will
be overwritten.

Simon

**Comment by egthomas** [comment]
@sshepherd yes I made a new change to `aacgmdlm.c`.  I can send you a copy of the modified file to drop into your local/master AACGM_v2 directory so it's not overwritten.

Am I interpreting the `/trace` keyword correctly that it is the same as choosing the field-line tracing option with the online calculator?

**Comment by sshepherd** [comment]
I believe so but will have to confirm next week when I get back to the
office. The good news is that there doesn’t look like a new release will
happen anytime soon.

**Comment by sshepherd** [comment]
These changes and bug fixes should get out quickly. The stand-alone AACGM-v2 code was updated and has been in use for several months by non-RST users. RST users are using old and buggy code but asking for the "patches" to the AACGM-v2 code. A better solution is to release a new version of RST quickly, with these and other changes.

**Comment by egthomas** [comment]
Ok, so the problem was related to an outdated `IGRF_COEFFS` environment variable in `superdarn.bash` and `superdarn.tcsh`.  Repeating my test from before,

With the DLM:
```
IDL> print,aacgm_v2_setdatetime(2018,08,1,00,00,00)
% Loaded DLM: AACGMDLM.
           0
IDL> pos=cnvcoord_v2(60.,120.,300.)
IDL> print,pos
       55.955571      -166.05710       1.0456635
IDL> pos=cnvcoord_v2(60.,120.,300.,/trace)
IDL> print,pos                            
       55.957024      -166.05854       1.0456635
```

However, without the DLM:
```
IDL> print,aacgm_v2_setdatetime(2018,08,1,00,00,00)
       0
IDL> pos=cnvcoord_v2(60.,120.,300.)                
% Compiled module: FACTORIAL.
IDL> print,pos
       55.955571      -166.05710       1.0456635
IDL> pos=cnvcoord_v2(60.,120.,300.,/trace)         
IDL> print,pos
       12.062125      -170.09346       1.0456635
IDL> print,getenv('IGRF_COEFFS')                   
/jumbo/superdarn/evan/test_rst6/rst/tables/analysis/mag/magmodel_1590-2015.txt
```

@sshepherd, are you sure the native IDL code is getting the paths correct?

**Comment by asreimer** [comment]
This is a touch off-topic, but I wanted to suggest a friendly solution to help with things like this in the future:

@sshepherd if this is such a critical fix, or you think it requires a higher priority due to severity of bugs, it's useful to communicate this from the beginning so people can prioritize. It's not really fair to complain otherwise. If you have, I missed it, and my comment is moot.

There are ways to deal with this though. For example, a "hotfix branch" or something similar could have been made with an RST4.1.1 release or whatever the version number should be. Easy for me to say, I know. I'll slink back in to the shadows now.

**Comment by sshepherd** [comment]
I will defer any decision regarding "hot fix branches", or whatever, to
those who are developing guidelines. This was (I think) identified in the
original request as a bug fix. My "complaints" are merely an attempt to get
changes into users hands more quickly than would otherwise happen. This is
not commercial software and should, in my opinion, be updated more
frequently with the caveat that we know there will still be bugs in the
code. Our more experienced users will likely identify these bugs. The
alternative is that we sit on code fixes, features, etc. for over a year
waiting for someone to decide that a new release is appropriate. As an
observer, I am suggesting that a new release is overdue.

**Comment by sshepherd** [comment]
Hmmm, something is probably not set correctly. I get the following
(correct) output when I disable the DLMs and run the attached test program:

Output:

COEFF:        55.955571      -166.05710       1.0456635
TRACE:        55.765593      -166.52621       1.0456635

oregon:~/Projects/AACGM/distro/idl/latest> setenv | grep DLM

IDL_DLM_PATH=
DLMPATH=

Simon

**Comment by egthomas** [comment]
@sshepherd attachments don't seem to survive when replying to github messages via email.  Can you re-attach the file to the pull request discussion using the github website?

**Comment by sshepherd** [comment]
Here is the contents of the file I call "newtest.idl" which I then run from the command line: "idl newtest.idl"





    .compile genmag
    .compile igrflib_v2
    .compile aacgmlib_v2
    .compile aacgm_v2
    .compile time
    .compile astalg
    .compile mlt_v2

    ch = ''
    fmt = '(a,$)'

    year  = 2018
    month = 8
    day   = 1
    ; hour, minute, second have little effect...

    ret = AACGM_v2_SetDateTime(year,month,day)

    ;-----------------------------------------------------------------------------
    ; test single input
    ;

    lat0 = 60.
    lon0 = 120.
    alt  = 300.

    p = cnvcoord_v2(lat0,lon0, alt)
    print, 'COEFF: ', p

    p = cnvcoord_v2(lat0,lon0,alt,/trace)
    print, 'TRACE: ', p
    print, ''

    exit

**Comment by egthomas** [comment]
And here is my output (when copying the IDL .pro files from this branch of the RST to a new directory):

```
babylon1:~/aacgm_test$ idl newtest.idl 
IDL Version 8.5.1 (linux x86_64 m64). (c) 2015, Exelis Visual Information Solutions, Inc., a subsidiary of Harris Corporation.
Installation number: 212858-3.
Licensed for use by: Dartmouth College

% Compiled module: AACGM_V2_DAYNO.
% Compiled module: AACGM_V2_DATE.
...
% Compiled module: MLTCONVERTEPOCH_V2.
% Compiled module: MLT_V2.
% Compiled module: FACTORIAL.
COEFF:        55.955571      -166.05710       1.0456635
TRACE:        12.062125      -170.09346       1.0456635

```

If I roll back to the master branch, the native trace option works correctly:

```
IDL> print,aacgm_v2_setdatetime(2018,8,1,0,0,0)
       0
IDL> print,cnvcoord_v2(60.,120.,300.)          
% Compiled module: FACTORIAL.
       55.955571      -166.05710       1.0456635
IDL> print,cnvcoord_v2(60.,120.,300.,/trace)
       55.957022      -166.05854       1.0456635
```

Are you sure the IDL code to parse and load the pre-1900+IGRF coefficients within the RST is working correctly?

**Comment by egthomas** [comment]
The above fixes to the native IDL code were forwarded to me from @sshepherd since he is traveling to a radar site today.  I've tested them and the `/trace` keyword option is now fixed.  With that taken care of and the C code already having been tested (by myself and @aburrell), I'm merging this pull request.

**Comment by ksterne** [comment]
self merging, *high brow*.  Though it does seem like this has been fairly well tested and if anything the pull request could have been said to originate from @sshepherd as he's been making the fixes that are then translated to rst.  I don't have a problem here, though lets try not to do that too much.

**Comment by sshepherd** [comment]
I suggest we try and avoid these type of unhelpful comments in the future.
The release of an updated RST is long overdue and attempts to move the
process along are only met with resistance and further delays. The RST is
not commercial software and should not be treated as such. Updates should
get to users quickly.

**Comment by asreimer** [comment]
I completely agree with @ksterne.

I completely disagree with @sshepherd about the comment being unhelpful.

There is a process and it must be followed, otherwise what is the point of having it. As an observer, I would say is it appropriate for @sshepherd to encourage people not to follow the process that the working group has established.

And nothing @ksterne did slowed the process. He didn't revert the merge. @sshepherd made a comment in several places that a new release of RST is long overdue. The response to this has been the largest flurry of activity on this repo in months. My inbox has been absolutely slammed with RST updates the past 2 weeks (which is awesome!).  People, especially @egthomas, @ksterne, @mts299, and @kkotyk  have made a significant effort to get a ton of pull requests merged. Literally spending entire days on mostly RST development (judging from the email alerts I received).

**Comment by egthomas** [comment]
Except @ksterne went on to admit the pull request originated from @sshepherd and that it really wasn't a self merge, so the sarcastic "high brow" comment was entirely unnecessary.

**Comment by asreimer** [comment]
Did it though? @egthomas made the pull request.

image

Sure, "high brow" was not needed, but that was hardly the point of @ksterne's entire comment. cherry picking aside.

**Comment by egthomas** [comment]
Is it really my pull request if 100% of the original code changes on the branch were made by someone else and I simply opened it for them on github and then tested it?  The rest of @ksterne's comment acknowledged that fact, which is why the initial sarcasm was unnecessary and unhelpful.

**Comment by asreimer** [comment]
Communication is important.

I have absolutely no way of knowing (and neither does anyone else) that this is actually @sshepherd's pull request if you make it and don't say that you made it for him. Not that it matters if you respect the process.

And again, his comment didn't slow any process at all. It was a caution against people merging their own pull requests, which is 100% not in line with the agreed to process.

The most inappropriate thing here is someone encouraging others to ignore the process.

But sure, let's continue down this trail of productive pedantry.

**Comment by egthomas** [comment]
You're right, this is going nowhere and the previous comments speak for themselves.

**Comment by ksterne** [comment]
Hey all, sorry for my colorful comment here, I didn't mean it in any seriousness and was only meant to be a slight joke.  My main intention wasn't to scold things here, I truly am happy with this pull request through and through.  I more meant to make a gentle reminder to other devs we shouldn't do this too much.  And somewhat for posterity as it looks like self merging though it only is on the face and not in content/context.

I am truly sorry that my joke had the opposite effect of what I meant here.  I'll try to keep this in mind for the future.

**Comment by sshepherd** [comment]
Ashton, are you contributing in a meaningful way to the RST effort or just
quick with your opinions on various procedural matters?

**Comment by pasha-ponomarenko** [comment]
I did not check my mailbox this morning, and here we are... 
Guys, cool down! 
Getting personal is not helpful at all, and sense of humour is an invaluable asset.

**Comment by sshepherd** [comment]
Appreciate the reply, Kevin, particularly while waiting for you in the Tim
Horton’s parking lot in Timmins. See you soon, I hope.

**Comment by egthomas** [comment]
Yes, thank you for clearing that up @ksterne - I'm sorry for misinterpreting your comment and apologize.

**Pull request merged**
