### PR TITLE
Feature/aacgm v2

### PR DESCRIPTION
**Pull request by sshepherd**
Adding capabilities of AACGM-V2, MLT-V2 and IGRF-V2 to the RST. New directories were added to src.lib under codebase/analysis so that both old and new version of AACGM, MLT, and IGRF could be called, i.e., both are compiled when RST is built. No modifications to the gridding, plotting, etc. code was made to call the new -V2 functions, this is simply the addition of new libraries to RST.

There are a few bug fixes to the astalg functions that impact the new libraries.

The test is to (1) make sure it builds and the new libraries are created and (2) call test_aacgm after the build and see if the output makes sense. This is a test program inserted in the src.bin directory under codebase/analysis.

### CODE REVIEW

**Comment by egthomas** [comment]
I just tried compiling this from a fresh clone of the repository and received the following error:

`================================================================================`
`Compiling Library:/rst/codebase/analysis/src.lib/mlt/mlt.1.4`
`================================================================================`
```
make clean
rm -f *.o
make
make.version /rst/codebase/analysis/src.lib/mlt/mlt.1.4/src/..
make.hdr /rst/codebase/analysis/src.lib/mlt/mlt.1.4/src/../include /rst/include/analysis 
/rst/codebase/analysis/src.lib/mlt/mlt.1.4/src/../include/mlt.h
'/rst/codebase/analysis/src.lib/mlt/mlt.1.4/src/../include/mlt.h' -> '/rst/include/analysis/mlt.h'
cc -fPIC -Wall -O3 -ansi -D_GNU_SOURCE -D_LINUX -I/rst/include/base -I/rst/include/general -I/rst/include/analysis -c mlt.c    
mlt.c:35:20: fatal error: astalg.h: No such file or directory
compilation terminated.
/rst/build/make/makelib.linux:19: recipe for target 'mlt.o' failed
make: *** [mlt.o] Error 1
Compilation Aborted.
```

Does the capitalization of "astalg.h" (vs AstAlg.h) make a difference here?

**Comment by egthomas** [comment]
Simon and I took a look at this and realized there were two problems:

1) this pull request depends on the bug fix to makeall (see pull request #21), which solves the issue with header files identified in my previous comment
2) a few environment variables were missing (AACGM_v2_DAT_PREFIX and IGRF_COEFFS) that needed to be added to the superdarn.bash and superdarn.tcsh profiles

My recent commit (	126660b ) fixes the latter while the former depends on Simon's makeall bug fix / pull request (#21) being accepted.  After implementing these locally, I was able to successfully compile the feature/aacgm_v2 branch and execute test_aacgm.

**Comment by ksterne** [comment]
Does this pull request depend on having IDL?  I cherry picked the one commit ecc0e7b from #21 and I'm still getting the mlt.o failed.  But this is on a setup that doesn't have IDL so I've deleted the `~/codebase/superdarn/src.lib/tk/idl/` directory.  So, I'm wondering if that's my problem.

Also, @sshepherd, you noted about modifying the astalg.pro code.  Mind if I check and add some notes if necessary on a bug that Rob Fear found a year or so ago?  It had something to do with a year variable being treated strangely, so maybe the change here that Nathaniel had passed along can get things fixed up.  I'd like to test it though to see.

**Comment by egthomas** [comment]
This branch predates the fixes I introduced for compilation without access to IDL, so you're correct that you need to either delete or tar the codebase/superdarn/src.lib/tk/idl directory for compilation to work.

**Comment by ksterne** [comment]
Yes, I have deleted `codebase/superdarn/src.lib/tk/idl/` and the compilation here does not work.

**Comment by sshepherd** [comment]
Can you list your error? You need some of the other commits as listed in Evan's note.

**Comment by egthomas** [comment]
Did you unset the $DLMPATH environment variable?  That was also a necessary step to prevent the DLMs from being compiled without access to IDL.

**Comment by ksterne** [comment]
As noted before...here's my compilation failure point:

```
================================================================================
Compiling Library:/home/ksterne/Documents/rst_sandbox/rst/codebase/analysis/src.lib/mlt/mlt.1.4
================================================================================
make clean
rm -f *.o
make
make.version /home/ksterne/Documents/rst_sandbox/rst/codebase/analysis/src.lib/mlt/mlt.1.4/src/..
make.hdr /home/ksterne/Documents/rst_sandbox/rst/codebase/analysis/src.lib/mlt/mlt.1.4/src/../include /home/ksterne/Documents/rst_sandbox/rst/include/analysis 
/home/ksterne/Documents/rst_sandbox/rst/codebase/analysis/src.lib/mlt/mlt.1.4/src/../include/mlt.h
'/home/ksterne/Documents/rst_sandbox/rst/codebase/analysis/src.lib/mlt/mlt.1.4/src/../include/mlt.h' -> '/home/ksterne/Documents/rst_sandbox/rst/include/analysis/mlt.h'
cc -fPIC -Wall -O3 -ansi -D_GNU_SOURCE -D_LINUX -I/home/ksterne/Documents/rst_sandbox/rst/include/base -I/home/ksterne/Documents/rst_sandbox/rst/include/general -I/home/ksterne/Documents/rst_sandbox/rst/include/analysis -c mlt.c    
mlt.c:35:20: fatal error: astalg.h: No such file or directory
compilation terminated.
/home/ksterne/Documents/rst_sandbox/rst/build/make/makelib.linux:19: recipe for target 'mlt.o' failed
make: *** [mlt.o] Error 1
Compilation Aborted.
```
Here's my output of `git log` going back a few commits:

```
commit 3b8c8e076c61342725507fd72c321bb4293a5510
Author: sshepherd <simon.shepherd@dartmouth.edu>
Date:   Wed Feb 22 12:45:40 2017 -0500

    Bug fix to makeall. Major version increment was not tracking properly.

commit 77a58d2f5a511bb87944f0175ba4d595514f6211
Author: sshepherd <simon.shepherd@dartmouth.edu>
Date:   Wed Mar 8 15:40:22 2017 -0500

    Making global variables static to work with RST library.

commit 973629a3d935fd6a65f2c6922c47332bc195d7b3
Author: sshepherd <simon.shepherd@dartmouth.edu>
Date:   Mon Mar 6 12:30:12 2017 -0500

    Changing internal function filename so it does not conflict with corresponding function in old AACGM

commit 126660b2f6cc932b1435af3bc0cd62aac8878ab2
Author: egthomas <evan.g.thomas@dartmouth.edu>
Date:   Mon Feb 27 13:26:54 2017 -0500

    Adding AACGM_v2 and IGRF12 environment variables to superdarn bash and tcsh profiles

commit 0aae9b60dafc6774fcede9b30579ea765a6440bc
Author: sshepherd <simon.shepherd@dartmouth.edu>
Date:   Thu Feb 23 16:42:13 2017 -0500

    Integration of AACGM-v2, MLT-v2 and IGRF-v2 into RST

commit 89b7fd246921fae2a27b1e9d6d9fa64de2a6f2ca
Author: sshepherd <simon.shepherd@dartmouth.edu>
Date:   Wed Feb 22 12:22:13 2017 -0500

    AAGCM_v2, MLT_v2, IGRF_v2: changing directory structure to allow for compilation of old and new versions to exist

commit d76be495ed09b71225fab1c295d9ebddd5fe9de7
Author: sshepherd <simon.shepherd@dartmouth.edu>
Date:   Thu Feb 16 14:54:02 2017 -0500

    Adding missing IDL directories for aacgm, asalg, igrf, and mlt
```

You can see there's the commits in this pull request as well as the one from #21 that I cherry-picked on top.

Also, `echo $DLMPATH` yields a blank line....so, it's not set?  I've done the usual non-IDL steps that I've done before.

**Comment by sshepherd** [comment]
This is MLT (not MLT_v2) not finding the change to the astalg.h file which indicates that you do not have the makeall fix working and you are are not building the astalg.2.0 library. Check to see if that is the case. Evan noted this exact problem in a comment above.

**Comment by egthomas** [comment]
So I tested compilation of this branch as-is on a Debian 8.7.1 virtual machine and test_aacgm actually works even without pulling/cherry-picking the makeall fix from #21.  Compilation on OpenSUSE and Mint does fail at the same point however.

Merging the develop branch into feature/aacgm_v2 has resolved the issue on all of my test cases.

**Comment by ksterne** [comment]
Doh, seems as though the same thing that tripped me up in #21, got me here.  Forgot that re-running `make.build` was necessary.  I've got it to compile now.

Running the test_aacgm seems to work, though I can't say anything about the content that is output.  If anything it looks funny that the conversion from geographic to AACGM-v2 and back doesn't result in the same value.  The value does come back with the field-line tracing.  Is this an expected behavior?  If so, I think that it should be noted here.  As well, since this is a testing routine, can an expected result be printed out somewhere so that a tester can match the numbers easily?  When I think of a testing routine, I think of a print out like:

```
The expected values are:   4  5  7
The calculated values are:  4  5  7 
```
Where the first line is just an fprintf of hardcoded values, but the second line is using the calculated values from the routine.

Is there a reason to keep aacgm and aacgm_v2 differentiated?  Or another way to think about it, is there a reason to keep aacgm (v1) around?

Lastly, if the test_aacgm package is testing the v2 and we're keeping v1, then why isn't it call test_aacgm_v2?  Seems to make more sense to keep it lined up with the naming scheme.

**Comment by ksterne** [comment]
As a follow up, the bug that Rob Fear had noted to me has been cleared up by https://github.com/SuperDARN/rst/blob/8ca319b1b1ccf781e84bcface70595131fd912e9/codebase/analysis/src.idl/lib/astalg.2.0/astalg.pro#L78-L82.  So, it's good to see someone else found that out and has corrected it.  I'll await a response to my previous comment.

**Comment by sshepherd** [comment]
The transformations are not perfect:

Baker, K. B. and S. Wing (1989), A new magnetic coordinate system for conjugate studies at high latitudes, J. Geophys. Res., 94(a7), p. 9139, doi:10.1029/JA094iA07p09139.

Shepherd, S. G. (2014), Altitude-adjusted corrected geomagnetic coordinates: Definition and functional approximations, J. Geophys. Res. Space Physics, 119, 1â€“21, doi:10.1002/2014JA020264. preprint (note that figure numbers may not have been processed correctly.)

The latter paper describes this in more detail and the whole point of adding the field-line tracing option.

The stand-alone AACGM-v2 package: http://engineering.dartmouth.edu/superdarn/aacgm/c_aacgm_v2.3.tar has something like this. Adding something like this is fine.

The reason to keep AACGM and AACGM_v2 separated is that the they are NOT compatible (see the latter reference.) Keeping AACGM is important if you want to reproduce results, however incorrect they may be.

To be clear, this branch only adds the AACGM_v2, MLT_v2, IGRF_v2 libraries. It does NOT provide functionality of these routines. That is much harder and Evan and I are working on that with gridding, plotting and map potential.

The naming scheme is intended so that anyone could put testing routines for AACGM or AACGM_v2 in the same directory. These are only intended to satisfy the testers. The real test is when they are implemented in the procedures listed above.

**Comment by ksterne** [comment]
Thanks for the references, I probably won't have time to look through them.  You are reminding me though that I've heard the transformation isn't quite reciprocal, so that does make sense it's not coming back to the same point.

Sounds good on the additional aacgm instead of the replacement.  I can appreciate the need to keep legacy code for reproduction of results.

For the testing, I guess my note was more that the binary called is `test_aacgm` without any note of version on it.  But, I think what you're getting at is that additional version 1 test code could be added to this same binary?  I could see that, though I think it's more straight forward if you're calling a test of one aacgm version.  It would also be confusing to include aacgm v1 test within a directory 

Do you agree on the expected results being printed out in the test call?  If so, is the expected result for this conversion:
```
TEST: geographic to AACGM-v2
    GLAT             GLON            HEIGHT         MLAT            MLON          R
    45.500000        -23.500000      1135.00000     48.189618       57.763454     1.177533

TEST: AACGM-v2 to geographic
    MLAT             MLON             R             GLAT            GLON         HEIGHT
    48.189618        57.763454        1131.097495   45.440775       -23.472757   1134.977896
``` 
(sorry if the formatting is off a little, I had to re-type it out)  If you're OK with it, then I can add a print statement that includes these values that are expected and then have the test code print what is the calculated values.

**Comment by sshepherd** [comment]
I have no idea whether this commit worked since the messing around with files changed my local copy and a pull may have overwritten them. I suggest we stop with minor formatting edits before this request is accepted.

**Comment by ksterne** [comment]
@sshepherd, this looks good.  I know it's a pain, but I think this is a great example going forward with providing test code.  

As for the issues there, while it's not usual, it's completely possible to make edits to a branch where-ever it is.  So, before starting to do some work, it's a good idea to do a `git fetch` and/or `git pull` so that you can see if anyone else has made some edits.

I'll merge this in for now.

**Pull request merged**
