### PR TITLE
Implementation of new --version option to print current RST version number

### PR DESCRIPTION
**Pull request by egthomas**
This is a test demonstration of a new `--version` option which can be added to any command line binary that will print the current version number of the RST (stored in the newly added `rst.version` file in the home directory) and exit.  To test, try executing

`aacgmeval --version`

This was originally requested by @mtwalach in #163.

### CODE REVIEW

**Comment by mtwalach** [comment]
Yes, this is what I had in mind. I tried it and it does what it says!

**Comment by mts299** [comment]
Worked for me! I assume the version will change when it is merged in 4.2 as it currently reports 4.1?

**Comment by egthomas** [comment]
Yeah, that's something we can update on the 4.2 release branch.  @ksterne can correct me if I'm wrong, but I believe the merging order goes something like

`develop` -> `release branch` (new branch)
`release branch` -> `master` (merge)
`master` -> `develop` (merge)

**Comment by kkotyk** [comment]
Good to merge then?

**Comment by egthomas** [comment]
I can add this option to some of the other binaries and include them with this pull request.  Should only take a few minutes.

**Comment by mts299** [comment]
Depends, if it holds more than just RST version I think version.txt is okay but if it is only rst then RST_VERSION.txt would be more clear

**Comment by mts299** [comment]
The version option works for me.

One thing I did notice was that savetodmap --help did not print anything?

**Comment by egthomas** [comment]
I think that's because there is no doc.xml file for savetodmap which populates the help output. I may have added one in the option error handling pull request but it's been so long I don't remember.

**Comment by mts299** [comment]
Okay, I was not sure because I saw the -help option in the code so figured it had one. Should we add one or make that another issue/ PR to make savetodmap doc? 

Otherwise, I think this PR is good to be merged.

**Comment by egthomas** [comment]
I think once this pull request and #144 are merged then it will be easier for someone can go back and look for missing help documentation.

**Pull request merged**
