### PR TITLE
Update README.md for CentOS

### PR DESCRIPTION
**Pull request by aburrell**
Updated README with package instructions for the CentOS operating system.

### CODE REVIEW

**Comment by asreimer** [comment]
See discussion in #215. I think the direction being taken here is to put all installation instructions in to an `INSTALLATION.md` file or something like that in the root directory of the repo. There's also been some recent discussion about using readthedocs.

In the mean time, there are instructions (here)[https://github.com/SuperDARN/rst/wiki/Installation-Guide] for CentOS 7, but nothing yet for CentOS 6, so they could be added there.

**Comment by aburrell** [comment]
@asreimer until the INSTALLATION.md file is added, it looks like the README.md is still the right place to record this information.  I added a line to the wiki, though I can't confirm the yum statement, since I don't have the appropriate permissions on the system I'm using.

**Comment by asreimer** [comment]
Note #164.

**Comment by aburrell** [comment]
Noted.  I just don't see the point in making things hard to find.

**Comment by asreimer** [comment]
That's a valid concern, but not the problem. The issue is that if we keep adding installation instructions into the README in the current format, that table will be pages wide, which is not helpful. Also, it's nearly impossible to read that table with a text editor.

Point is we need a better solution. I think I'm hearing that you like the INSTALLATION.md idea, which is what the discussion in #215 was sort of also coalescing on too. I'm waiting for some more feedback in there and then I'll make a PR to introduce an `INSTALLATION.md` file.

**Comment by aburrell** [comment]
If there is an INSTALLATION.md file or some other update to the README.md that replaces the table, then I will retract this pull request.

**Comment by ecbland** [comment]
The only proposed change here is to add the list of packages for another OS (i.e. a new column). I can see that we are running out of space for more columns, so a simple solution for now would be to reformat the table into a horizontal list for each OS, i.e. 

---
**Debian 8.7:** gcc  libhdf5-serial-dev  libnetcdf-dev  libncurses  libpng12-dev  libx11-dev  libxext-dev  netpbm
**Mint 18.1:** libc6-dev libncurses5-dev libnetcdf-dev libpng16-dev libx11-dev libxext-dev
...
...
**CentOS 6.10:** [wow, it's really slow to copy & paste from the table!]

---
Not as pretty as the table but it is much easier to copy & paste into a terminal :) Would this be acceptable @aburrell @asreimer ? 

We have several decisions to make regarding the documentation, but I think this PR can be dealt with in the scope of the current README file.

**Comment by asreimer** [comment]
@ecbland ya that's a good compromise IMO. I'll work on that now.

**Comment by asreimer** [comment]
Hmmm. Given discussion in #210 leading to the `doc/read_the_docs` branch, I have another question actually. I'm going to ask this question in #215.

**Comment by ecbland** [comment]
@asreimer Now that this information is in readthedocs, I guess we can close this PR (without merging)?

**Comment by ksterne** [comment]
@ecbland, good catch on the readthedocs only having CentOS7.  I've updated the `doc/read_the_docs` branch.  Can @asreimer or @mts299 check things out here?  I think that should close this PR if so.  I should note, I've just moved the notes from @aburrell and haven't tested this myself.

**Comment by mts299** [comment]
I checked things out and did one fix from what you added @ksterne. Thank you for updating this! 

Closing PR and hoping to make a new PR with these changes and more within in the week :)

**Pull request closed without merging**
