### PR TITLE
4.3.1 release

### PR DESCRIPTION
**Pull request by ksterne**
This patch release is to get the AACGM v2.6 update (#261) out as a general release since it's been determined that there is a more urgent need to have this released and it cannot wait for 4.4 release.  This should be a quick check/test here so I'll merge it in on Feb. 3 if there's no objections on how this looks/functions.  This should give some time for people to review and comment.

We will still proceed with release 4.4 as scheduled about 3 weeks after this release.

### CODE REVIEW

**Comment by egthomas** [comment]
@ksterne could you clarify why this needs to be treated as a patch rather than a minor release?  That would simplify the merging procedure by allowing you to include the other already-approved changes on the develop branch rather than cherry picking.  And I don't recall any extra testing time being required for minor vs patch releases:

```
- No more than two weeks of testing should be performed on each new MINOR release branch before merging into the master branch
- No more than one week of testing should be performed on each new PATCH release branch before merging into the master branch
```

**Comment by ksterne** [comment]
This is being treated as a patch as it's one feature that is critical to being released rather than other parts.  Minor release would require longer testing period and is already in the works that was agreed upon during the last Data Analysis WG meeting.

**Comment by sshepherd** [comment]
Good news, Kevin. I think it best that someone else test the installation and whether the test functions work after recompiling. Evan set things up here so it might be redundant for me to test. I don't expect any different behavior from the previous version since the DLMs shouldn't change.

**Comment by egthomas** [comment]
@ksterne ok thanks.  In that case the text of the release guidelines should probably be changed to reflect the longer testing periods now being required (rather than only an upper limit being defined).

**Comment by ksterne** [comment]
Looks like we're good to go here.  I'll send out a note to the darn-users list.  Someone (maybe Simon or Evan) could you also send out an e-mail to the SPA newsletter as a follow up if it's appropriate?

**Comment by egthomas** [comment]
@ksterne just noticed that the `rst.version` file was not updated to reflect this patch release.

**Comment by ksterne** [comment]
Ah crud.  I'd say it's not worth fussing over as we'll have a 4.4 out soon enough.  Others thoughts?

**Pull request merged**
