### PR TITLE
4.4.2 release

### PR DESCRIPTION
**Pull request by ksterne**
This is a bit of a short description on the release and I've only gotten items 1 through 5 on the list together.  I wanted to get this started as an initial/draft way for doing the ordering for authorship.  

My basic idea was looking over the last roughly year (since version 4.3 was release) on the number of commits to determine the order. I've elevated @mts299 higher here as a show of direct involvement in testing and creating for this release branch.  Otherwise, after @asreimer, these are in alphabetical order as they have not had an commits over the last year, but have still contributed to this code in the past.  I'm certainly open to thoughts on ordering as this is the first time trying this out.

I'll mark this as a draft release and we should get it merged by Oct. 6th (if not sooner).  This test here is to make sure I've captured the bugfixes that were applied in (and mentioned in #341):

- [ ] #340 
- [ ] #331 
- [ ] #332 
- [ ] #321 

I'll work on going through the checklist up to merging point 10 either tonight or tomorrow and once I'm done with these I'll change it from being a draft.

EDIT: (removed unintentional link on the 10 issue or PR)

### CODE REVIEW

**Comment by ksterne** [comment]
Confirmed with Ubuntu 20 install that the compilation is failing.  Seems as though it's on the comment line in:

https://github.com/SuperDARN/rst/blob/97eaa1907fa93891cc92ef707ca6e34ee01f05bc/codebase/superdarn/src.bin/tk/tool/make_fit.1.19/make_fit.c#L491-L495

So, two options I see going forward.  Also cherry pick in the commits from #293 or change the way this line is commented.  I'm in favor of the later as I think the first one gets into scope creep of what we're doing for this patch release.  Any thoughts otherwise or maybe another option I've missed?

**Comment by mts299** [comment]
@ksterne Actually its because its still running C90 compilation. 

>   -ansi  
Is in the line for compiling. 

How did this get merged back in?

**Comment by mts299** [comment]
We are also missing #313

**Comment by mts299** [comment]
@ksterne for authorship I was actually thinking this one could be split with 3 contributors and alphabetic. 
@mts299 @egthomas  @ecbland 

One big fix @ecbland was helpful for debugging with me. @egthomas actually solve 3 bugs and @ecbland tested and edited a lot of documentation.

**Comment by egthomas** [comment]
I'm afraid I must respectfully disagree with the extent of this pull request in terms of commits / bug fixes and repeat my concerns voiced earlier this year over the DAWG mailing list with regards to patch releases (specifically in reference to how the AACGM-v2 and IGRF updates were treated as a patch but no other bug fixes were allowed at that time).

My personal feeling is that patch releases should be reserved for fixing functionality which was working in a previous release.  And let me be clear that I am not saying this to pick on anyone; in the past I've broken several routines which were not noticed until after a minor release was made - these things happen, and "fault" is not a word that should ever enter the discussion.  The plotting and DLM bugs were present in all previous iterations of RST from 4.0 onwards, whereas the compilation and make_fit bugs were not; I believe that should be where we draw the line on a patch.  Also, I do not believe this practice of cherry picking commits is fair to developers, as we cannot be expected to make changes which are always compatible with both the `develop` and `master` branches (e.g., the compiler updates which have been in place on `develop` for some time but are not yet implemented on `master`).

I also think I raised this point on the release guideline or authorship documents on the internal dawg repository, but I do not believe the author list should be modified between a minor and patch release.  What is more significant - the changes to functionality which warranted a minor release, or the subsequent bug fix or two included in the patch release?  Especially since the latest version of the software is likely to be the most often cited.

**Comment by ecbland** [comment]
@egthomas You've made several good points here; thank you. I definitely agree that there's a difference between fixing old bugs and fixing bugs that weren't there in the previous release. We should clarify this in the release guidelines. 

> I do not believe this practice of cherry picking commits is fair to developers, as we cannot be expected to make changes which are always compatible with both the develop and master branches (e.g., the compiler updates which have been in place on develop for some time but are not yet implemented on master).

Indeed! And yes, the compiler update is the reason that this branch doesn't compile, but that can easily be fixed.

Perhaps we should make the patch only to fix the `make_fit -old` bug, and everything else can wait until the next minor release? I'm not sure that we are ready for a minor release now, but we could discuss that option...

**Comment by mts299** [comment]
I am okay with changing the `make_fit -old` bug to work with C90 but this is a bit of backward pedaling that seems unnecessary and for future fixes annoying because are we basing fixes on `develop` or `master` right now. 

Also, a user came to me about the plotting bug in the southern hemisphere, are we to deny the user from plotting until a minor release? If they want to publish they cannot use `develop`, what do I say to them?

Kathryn is also waiting on the RAWACF documentation, fixes on FITACF documentation for the data task force, and achieving her code? Are we still to deny her of this? 

What about the error message Emma got? Or CDF clarification and Field of View bug that a user came to us? 

Patch releases should be bug fixes old or new so that users can use the code, who are we to say what bugs are important to each user? By making them wait we are providing a poor frustrating service. People make mistakes and blame are not here but we need to also account and fix our mistakes. 

Side note: hotfixes are the ones that are new and break the compilation essentially those are not the same as patch fixes.

**Comment by mts299** [comment]
I think we need to watch how and when we merge code, this is a bit of scope creep but if you want to wait longer on something to be merged then make it a draft as I did with FITACF 3.0.

**Comment by ksterne** [comment]
Thanks for the great points here!  Sorry we were able to capture this in #341 before making it to PR stage.  My apologies as well for a lengthy response, I'll try to keep it brief.  I wasn't wanting to include more to avoid scope creeping this patch release.  It might be just definition of terms or vision on what a patch release is so it's likely a good idea that we help better guide this with the release guidelines.  We'll continue that discussion there.  

For now, I think it is good to keep in mind that this patch release should fix things that were broken in a previous minor/patch release.  I think there's also merit in applying small updates (very few lines of code are changed) where someone is actively encountering a problem.  This seems to be a good way to satisfy the person that presented the problem and shows we're being responsive where there is not a large amount of change.  From the current list of PRs, I think the 4 I've got now (and in the original posting) are still good.  If there are others that might fit this description, feel free to bring them up.

Understand there is a need to add other functionality and documentation as there are other needs here.  It's been 3 months since we've had a minor release, so it's likely time we consider what the scope of that release will be.

My apologies on forcing the authorship order here a little early.  I'll revert it back and we can revisit this a little later.  The only thing I'll clarify here is that I'd determined this (and I think we'd noted this in some meeting discussions) that the order more reflects not just the current release, but also some X amount of history.  So this is why I'd look at things over the last year since v4.3 was released in early Sept. 2019.

So for now, I'll take action to revert the authorship ordering and change the `make_fit.c` line in order to restore compatibility.  I understand this is a backpedal on #293, but it is one line of code and when the merge conflict comes up, we can use the `develop` version.

Again, apologies for the lengthy comment.

**Comment by mts299** [comment]
I am still not understanding why we are not including #293 it does nothing different. 
Also all the missing PRs I listed where most are documentation which as stated in the guidelines cannot warrant a release but nor should they wait for a specific release. 
Patches are not to be a single PR release that's a HOTFIX. Patches are updates to the code in either a group or not that are not related to a new feature. 

The only code so far pushed in develop is snding library that would warrant a minor release.

**Comment by mts299** [comment]
Patch release:
> A release is a patch when the internal API of a module is not changed. So all internal method-signatures are unaffected, and there is no change in the call-flow or behavior of any method.
https://documentation.spryker.com/docs/major-minor-patch-release

PR #293 does not change anything of the code nor does it change the behavior of the flow.

**Comment by egthomas** [comment]
Like @mts299, I am also confused.  It seems arbitrary to pick and choose some pull requests that have been merged into develop but not others when addressing an unrelated yet critical bug.  For example, including #332 in this patch but not #319, when #319 actually addressed the concern raised by an external user (#302).

If we want to get changes out to users quickly, why not just include all of the approved pull requests and make a new minor release?  The release criteria have been easily surpassed and it's been nearly 3 full months since the last minor release.

**Comment by mts299** [comment]
@egthomas I think a minor release should be on your snding library I heard you want more time to work on that. 

Otherwise what is in develop excluding the snding lib stuff nothing is a new feature so a minor release is not warranted. Patch releases can have multiple updates to the code they can seem as big as a Minor release I have seen time and time again with security patches on computer OS's and other work software. 

If you think snding library is ready for a release then we can do a minor release. Otherwise, we should follow the definitions so users and future developers are not confused.

**Comment by egthomas** [comment]
#319 did add a new command line option to `grid_plot` which enabled users to only draw certain radar FOVs according to the contributing data.  So one could argue that was a (small) piece of new functionality.  Otherwise, once #327 is merged (in its current state) then the sounding library / binaries can be considered complete.

**Comment by mts299** [comment]
My bad I didn't know the new feature on grid_plot stuff. I thought that was a bug fix. 

Hard to say minor or patch is viable now depending on how we constitute a new option even though it is small. I think minor with the new grid_plot option with our bug fixes including the new C99 compiler is a good one. 

Sorry again @egthomas for missing that.

**Comment by ksterne** [comment]
Thanks for the perspective and resource @mts299 on an example of versioning.  This might be better suited for better supported software packages.  Under this thought, we would have made hotfixes for many of the PRs that have been discussed here.  I don't know that we're there yet as many of us don't have the time to support this kind of progression.  I'd like to kindly ask more discussion on versioning be more directed to the PR in the dawg repo as that seems like a better place to continue that discussion.  I understand it's coming here as we're seeing the practical application of those guidelines here.

I also do not know that it's productive to here have a conversation on patch versus minor release as there's an issue where this was raised.  I do appreciate and understand all of the comments here as it's showing where we need to clarify things.  We'll work to make things clearer moving forward.  Otherwise, I think if we're able to quickly work through this patch release then we'll likely be looking at a minor release towards the end of October.  

For this PR though, I did consider adding #319 until I saw the number of lines added.  This is a pretty simple few of things, but thank you (collectively) for bringing it up that this PR does add an additional option. 

If we can agree we're good to go here, I'll mark this as ready to review and should check that the 4 bugfixes are still fixed with this release branch.

**Comment by mts299** [comment]
My vote is to scrap this PR (thanks for putting it up Kevin S) and make a release 4.5 with all the PRs add into `develop` minus snd library.

**Comment by ksterne** [comment]
After thinking this over some more, I think it's best to suspend anything on this patch release for now and instead focus efforts onto developing a minor release (4.5) that we could get out in the next month.  I'll only keep this PR and the draft release up incase the projected timeline for that minor release grows much longer than expected and we can get at least these small parts fixed sooner.

**Comment by ecbland** [comment]
Just to add to what @ksterne has said...this patch release came up mostly because of #338, which on the surface looks like a pretty substantial bug. However, it's my view that the fix for this bug can wait a few weeks while we put together a proper minor release because: 

1. It took more than 2 months for the bug to be reported, so it probably does not affect a large number of users
2. `dat` files should be converted to `rawacf` using `dattorawacf` in preference to using `make_fit -old`. So the bug should be avoidable in most circumstances.
3. If we're going to do a minor release in the next month-ish anyway, we can avoid asking users to reinstall RST multiple times in a short space of time. 



> @mts299 make a release 4.5 with all the PRs add into develop minus snd library.

I confirmed with @mts299 that the above was just a misunderstanding: of course @egthomas's `snding` library can be included in a minor release 😄

**Comment by mts299** [comment]
Should we close this since we are now talking about RST 4.5 release?

**Comment by ksterne** [comment]
We'll still keep this open from the previous comment about release 4.5 taking too long.  I think we're close, but not there yet.

**Comment by mts299** [comment]
Closing now that 4.5 release branch is done now.

**Pull request closed without merging**
