### PR TITLE
Simplifying make.code and make.doc commands

### PR DESCRIPTION
**Pull request by egthomas**
This pull request removes the unnecessary `superdarn rst` arguments from calls to `make.code` and `make.doc`.  These were only being used to label the log files - those filenames have now been hardcoded as `"${LOGPATH}/superdarn-rst.build.${dtval}"`.  Users can also still compile a single binary or library matching a particular pattern by entering something like `make.code bin make_fit` or `make.code lib gtable`.  The relevant portions of the README files have also been updated to reflect these changes.

### CODE REVIEW

**Comment by kkotyk** [comment]
I think this PR is a good change to make. If I use make.code bin make_fit, does it recompile all the dependent libraries?

**Comment by egthomas** [comment]
No, unfortunately it's not that clever.  I should also probably note that calling `make.code lib fit` will compile any libraries with names containing the string "fit" and not just the fit.x.xx library.  So it's not perfect but definitely useful when you don't want to recompile the entire RST.

**Comment by egthomas** [comment]
Not sure why a merge conflict appeared - clicking on d0c1f42 doesn't show anything for me.  Oh well.

**Comment by egthomas** [comment]
So anyone have a chance to take a look at this yet?

**Comment by kkotyk** [comment]
Yes, this works for me in Docker.

**Comment by egthomas** [comment]
Thanks!

**Comment by ksterne** [comment]
I know I'm a little late to the game here, but no warning for people using the old method and a deprecation warning?  Probably not a big deal since it's updated in the readme, hopefully we don't get a bunch of questions on it though.

**Pull request merged**
