### PR TITLE
Documentation for `fit_speck_removal`

### PR DESCRIPTION
**Pull request by ecbland**
This PR adds some basic information about the `fit_speck_removal` procedure to our readthedocs documentation.

You can preview the online documentation [here](https://radar-software-toolkit-rst.readthedocs.io/en/docs-despecking/user_guide/despecking/).

### CODE REVIEW

**Comment by pasha-ponomarenko** [comment]
@ecbland, I managed to dig out this email:

> On 15/11/2016 1:50 PM, Kevin Krieger wrote:
>> Hello,
>>
>> Twofsound.1.04 has been updated on all radars (except pgr due to 
>> network issues).  Prince George will be updated when it can be accessed.
>> It has CPID of 3505 for fast mode, and 3504 for regular mode.
>>
>> It sets channel to 1 or 2 depending upon the frequency.
>>
>> Kevin

I believe we can safely specify that we do not recommend application of the de-specking routine to the two-frequency data generated before December 2016.

**Comment by mts299** [comment]
So the readthedocs build works on readthedocs lol buuuttttt it fails here so ignore it

**Comment by ecbland** [comment]
> @mts299 My only comment is adding a second plot of the first plot showing the removal of the noise :) This will solidfy what it does and 

There is a "before and after" example in the last section of the documentation. 

> @mts299 maybe a nice thing is providing a line of how you plotted it in RST if you want.

I added instructions to make a RTI plot with `time_plot`

**Comment by mts299** [comment]
Okay I  think the before and after at the bottom was a bit confusing given the change in colouring of the plot

**Review by pasha-ponomarenko — APPROVED** [review]
It all looks good to me.

**Comment by ecbland** [comment]
@mts299 I replaced the figures in the example with figures made using RST's `time_plot`. The colour scale is different to the earlier plot because it shows velocity rather than power (I took this figure from a presentation I did a few years ago)

**Pull request merged**
