### PR TITLE
Updating hdw.dat files on master branch

### PR DESCRIPTION
**Pull request by egthomas**
This pull request (hotfix?) updates the Canadian hdw.dat files and adds the missing Longyearbyen hdw.dat file to the master branch.  It looks like a lot of lines were modified because there were a bunch of ^M escape characters from Windows in a few of the hardware files.  After verification from the USask and UNIS folks (@kevinkrieger , @kkotyk , @ecbland , etc) this should be merged as quickly as possible.

### CODE REVIEW

**Comment by kevinkrieger** [comment]
Yes the changes are appropriate to the best of my knowledge. Also had too few possible range gates (225 sometimes for 15km modes)

**Comment by kkotyk** [comment]
Paging the lovely @ecbland for approval of the Longyearbyen hdw.dat file!

**Comment by kevinkrieger** [comment]
You might want to get Mikko in on this, Emma's on holidays I believe.

**Comment by ecbland** [comment]
Sorry for the delay...yes, that is the correct version of the LYR hardware file.

**Comment by egthomas** [comment]
Great, thanks!  I'm going to go ahead and merge this so we can all start working with Longyearbyen data!

**Pull request merged**
