### PR TITLE
Updating version numbers for Release 4.0

### PR DESCRIPTION
**Pull request by egthomas**
This pull request increments the minor version numbers where changes to the functionality of the code was made.  So far, oldfitdlm, aacgmdlm, and make_grid have been updated in this pull request.  This can remain open until we're satisfied with the release-4.0 branch and are certain no other libraries/dlms/binaries need a new version number.

### CODE REVIEW

**Comment by ksterne** [comment]
For what it's worth, I got this to compile today without any problem.

**Comment by egthomas** [comment]
Ok, I think I've updated the minor version numbers for all of the libraries/binaries/dlms that have been modified in comparison to the old master branch.  There were probably other changes made in the VTRST3.5-era that this pull request will not track but overall it should put us in a better place moving forward.  If I've missed anything major (ie not just removal of spaces) please feel free to add it.

**Comment by ksterne** [comment]
Welp, looks like we've got a merge conflict here @egthomas.  Do you want to take care of it.  Guessing this happened from merging in the documentation update.  This is where direct commits to the release branch are good to do instead of the pull/merge that is done during usual development.

**Comment by ksterne** [comment]
On a side note, this still compiles for me, so I'll try merging it in in prep for tomorrow's new release.

**Comment by ksterne** [comment]
Looks like I've got it all in here, though maybe not so well noted on the commits.  @egthomas, you may want to check the release branch to see if the documentation on the fbuffer library is still good as that is what had a merge conflict.  Looks like the version number updated *and* the updates to the links are in there.

**Comment by egthomas** [comment]
What was the merge conflict here?  I don't remember seeing any earlier (and didn't run across any when doing a local test of merging everything into the release-4.0 branch on my machine).

**Comment by egthomas** [comment]
Sorry, somehow missed in your comment that it was related to the fbuffer library.  Looks fine to me.

**Pull request merged**
