### PR TITLE
Plotting fixes

### PR DESCRIPTION
**Pull request by egthomas**
This pull request makes numerous fixes to the plotting binaries, mainly through the addition of AACGM-v2 functionality to `field_plot` and `time_plot`, as well as adding `-png` to the list of available output file formats in the documentation and command line help.  Again, this was in response to a survey response which asked for more user-friendly output file formats (eg png or pdf) for the RST plotting.

Note that I still can't get `fov_plot` to draw any FOVs with the `-stereo` option for stereographic coordinates (although `-ortho` does seem to work).

### CODE REVIEW

**Comment by egthomas** [comment]
@ecbland - I'm out of the office right now so I can't test things, but I recall having issues reproducing the example output in the `fov_plot` documentation (https://superdarn.github.io/rst/superdarn/src.bin/tk/plot/fov_plot/index.html). Maybe I was missing the `-d date` option?

**Comment by ecbland** [comment]
@egthomas : Yes, you need the `-date` option. I figured this out by trial & error a few years ago. Certainly not obvious, and not included in the example you linked to. I guess it needs a date so that it only plots radars that were operational on the given date. It seems more sensible to make it default to the current date if nothing is provided.

**Comment by egthomas** [comment]
@ecbland - that makes sense.  `fov_plot` should now use the current date by default (but print a warning message saying the date should be specified).  That may have also been causing issues with the AACGM_v2 coordinates if an invalid date/time was being provided by default.

**Comment by egthomas** [comment]
@ecbland - I think I've fixed the `-ortho -mag` plotting bug.  Using the command `fov_plot -png -fov -st lyr -ortho -coast -d 20180510 -mag > fov1.png` I get:

fov1

This was due to undefined points near the equator being returned as `inf` by `AACGM_v2_Convert`.

**Comment by mts299** [comment]
So I am not sure if I am running the command correctly but when I try to plot velocity vectors I get nothing: 
sas_vec
I tried the following comands:

`field_plot -png -st 1:30 -square -grd -fcoast -coast -fov -fan -sf 2 -vec  -time -keyp ~/fitacf_files/20180413.C0.sas.fitacf > sas_vec.png`

`field_plot -png -st 1:30 -square -grd -fcoast -coast -fov -fan -sf 2 -vec -vkeyp  -time -keyp ~/fitacf_files/20180413.C0.sas.fitacf > sas_vec_vkeyp.png`

`field_plot -png -st 1:30 -square -grd -fcoast -coast -fov -fan -sf 2 -vec -vkeyp -vkey_path ~ -key rainbow.key -time -keyp ~/fitacf_files/20180413.C0.sas.fitacf > sas_vec_vkeyp_path.png`

Otherwise, field_plot works for other options:
sas_key_path
`field_plot -png -st 1:30 -square -grd -fcoast -coast -fov -fan -sf 2 -v -key_path ~ -key rainbow.key -time -keyp ~/fitacf_files/20180413.C0.sas.fitacf > sas_key_path.png`

sas_v_gs
`field_plot -png -st 1:30 -square -grd -fcoast -coast -fov -fan -sf 2 -v -gs  -time -keyp ~/fitacf_files/20180413.C0.sas.fitacf > sas_v_gs.png`

Also tested fov_plot and it seems to work as well. 

For time_plot there seems to be some overlapping of some of the numbers and letters like db and origin value along the y-axis. 

sas_time
`time_plot -png -ex 3:00 -gs -srng 35 -a -erng 60 -b 5 ~/fitacf_files/20180413.C0.sas.fitacf > sas_time.png`

**Comment by egthomas** [comment]
@mts299 the vector plotting in `field_plot` should now be fixed.  The axes labels in `time_plot` are beyond what I have time to do right now.

**Comment by egthomas** [comment]
It should also probably be noted the plotting tools don't need to be publication-quality, they're meant as more of a quick-look tool.  The main purpose of this pull request was to fix broken features and prevent seg faults.

**Comment by mts299** [comment]
@egthomas - Looks good to me.

sas_vec

 Cannot find any other bugs. Should I also test the other plotting binaries or is this PR's scope only focused on fov_plot, field_plot, and time_plot? 

Also, should I make an issue on the duplicate lettering just in case one of us has time to fix that?

**Comment by egthomas** [comment]
@mts299 I think there were also some fixes to `grid_plot` and `map_plot` but I don't remember the specifics.

**Comment by pasha-ponomarenko** [comment]
I wonder if there should be any sort of disclaimer (somehting like "Not for publication") or copyright statement added to the RST-produced graphics.

**Comment by egthomas** [comment]
@pasha-ponomarenko speaking as someone who's tried watermarks on scientific figures, users just crop those disclaimers out if they really want to include a figure in a poster/presentation/paper.

**Comment by mts299** [comment]
@pasha-ponomarenko I have not tested grid_plot or map_plot yet. I can do that right now.

**Comment by pasha-ponomarenko** [comment]
Up to you, @mts299!

**Comment by mts299** [comment]
grid_plot: 
In the plotting examples they have stereo: 
`grid_plot -ps -dn -st 12:00 -stereo -mag -rotate -fcoast -coast -fterm -tmk -vecp -vkeyp -time -raw -vkey ~/key/superdarn.key 20021219.grdmap
`
However, if you try to run this command (with real data) you get: 
Option not recognized: stereo
Please try: grid_plot --help
So the documentation needs to be updated, also ~/key/superdarn.key this is a bit confusing as I thought the ~ meant home directory not rst home. Maybe some clarification would be nice :p 

Once I get the options right, I get a good looking plot: 

`grid_plot -png -dn -st 12:00 -mag -rotate -fcoast -coast -fterm -tmk -vecp -vkeyp -time -raw -vkey_path ~/ -vkey rainbow.key ~/convection_20180623/20180623.grd`

Something doesn't seem right here:

`grid_plot -png -t 12:00 -pad 0 -mag -lat 84.4 -lon 55.00 -square -sf 2.00 -fcoast -coast  -vecp -xkeyp -time -raw -max -pwr -xkey_path ~ -xkey rainbow.key ~/convection_20180623/20180623.grd`

 Then I tried with no padding and using -et options:

`grid_plot -png -st 10:00 et 11:00 -tn -mag -lat 84.4 -lon 55.00 -square -sf 2.00 -fcoast -coast  -vecp -xkeyp -time -raw -max -pwr -xkey_path ~ -xkey rainbow.key ~/convection_20180623/20180623.grd`

It did not stop at 11 am?

**Comment by mts299** [comment]
map_plot:
Plots look good and it stops at the end time: 

`map_plot -png -dn -st 09:00 -et 11:00 -mag -rotate -fcoast -coast -fterm -tmk -vecp -vkeyp -time -imf -modn -pot -fit -ctr -vkey_path ~ -vkey rainbow.key ~/July2017FITACFTEST/20170701.map`

By accident I ran this command right away:
`map_plot -stdout -xml -t 6:00 -pad 0 -mag -lat 78.4 -lon 16.00 -square -sf 2.00 -fcoast -coast -vecp -vkeyp -grd -time -hmb -fit -ctr -vkey superdarn.key 20021219.cnvmap > map.rp.xml`
and I got a seg fault so maybe a file check would be good in map_plot. I noticed field_plot had one. 


`map_plot -png -t 6:00 -et 11:00 -tn -pad 0 -mag -lat 78.4 -lon 16.00 -square -sf 2.0 -fcoast -coast -vecp -vkeyp -grd -time -hmb -fit -ctr -vkey_path ~/ -vkey rainbow.key ~/July2017FITACFTEST/20170701.map ` 
Is -t suppose to only plot at that time? Otherewise, it seems to be doing the same thing at -st option. 


Not sure if adding the -ortho is suppose to change the look like the fov_plot did but it seems the same here:

`map_plot -png -t 6:00 -tn -pad 0 -mag -lat 78.4 -lon 16.00 -square -sf 2.0 -fcoast -coast -ortho -vecp -vkeyp -grd -time -hmb -fit -ctr -vkey_path ~/ -vkey rainbow.key ~/July2017FITACFTEST/20170701.map`

**Comment by egthomas** [comment]
> Is -t suppose to only plot at that time? Otherewise, it seems to be doing the same thing at -st option.

Presumably, but looking at the source code both `-st` and `-t` are stored in the same variable (`stmestr`; similar issue with the date options) so the `-t` option isn't working as it should.

On second thought, the fully gray plots are probably an issue with filling the terminator, possibly with aacgm_v2 coordinates.  I can look into that later this week.

**Comment by mts299** [comment]
> Using a ~ with the -key_path options could be causing the gray plots

I still get gray plots without the key_path and without -xkey as an option. 

`grid_plot -png -t 12:00 -pad 0 -mag -lat 84.4 -lon 55.00 -square -sf 2.00 -fcoast -coast  -vecp -xkeyp -time -raw -max -pwr -xkey rainbow.key ~/convection_20180623/20180623.grd`

> On second thought, the fully gray plots are probably an issue with filling the terminator, possibly with aacgm_v2 coordinates. I can look into that later this week.

I am thinking your assumption on aacgm_v2 is correct.

**Comment by egthomas** [comment]
@mts299 - the gray plotting bug should now be fixed (it was the same problem as when using AACGM_v2 with orthographic projections, which was previously fixed).

I also made one minor adjustment to the logic behind plotting IMF dials with `map_plot`; previously it would not draw the dial if any of the 3 IMF components were equal to zero (because that is their default value).  I've changed it to only **not** draw the clock dial if all three components are equal to zero.

**Comment by egthomas** [comment]
> @egthomas, unless there is a diagonal semi-transparent sign across the whole plot saying "Not for publication!"
;-)

Tried that and it still didn't work!

**Comment by mts299** [comment]
Looks like the AACGM_V2 fix worked: 

`grid_plot -png -t 12:00 -pad 0 -mag -lat 84.4 -lon 55.00 -square -sf 2.00 -fcoast -coast -vecp -xkeyp -time -raw -max -pwr -xkey rainbow.key ~/convection_20180623/20180623.grd`

I imagine you have not gotten around to the -t option problem?

**Comment by mts299** [comment]
Should I open an issue on possible plotting enhancements? Like a way to pick prefix to file names for grid and map_plot as well more clear wording on what is being plotted. I noticed if I plot spectral width vs. power it does not say anywhere what is being plotted just that the scale in dB.

**Comment by egthomas** [comment]
Sure, you can open a separate issue for discussing future plotting improvements.  No, I haven't done anything with the `-t` or -`d` options and probably won't have time to right now.  They're basically just duplicates of the `-st` and `-sd` options.

I promise I just made my final change on this pull request: `grid_plot` and `map_plot` will no longer plot vectors with saturated colors as black for 256-level color tables, but rather as the color of the highest level (eg as red instead of black for velocities exceeding `-vmax` with a rainbow-style color table).

**Comment by mts299** [comment]
> I promise I just made my final change on this pull request: 
As in your not working on it anymore? 

Also, am I putting something in wrong or is this another bug?

` map_plot -png -t 6:00 -tn -mag -pwr -fcoast -coast -xkeyp -logo -grd -time -hmb -fit -ctr -xkey_path ~/ -xkey rainbow.key ~/July2017FITACFTEST/20170701.map`

**Comment by egthomas** [comment]
You don't need to include the `-xkey_path ~/` option - that was a typo in the old documentation.  You can just use `-xkey rainbow.key` (without specifying any kind of key_path for any of the plotting binaries).

**Comment by mts299** [comment]
I tried that and it still came out with no colour.

**Comment by egthomas** [comment]
@mts299 - should be fixed, let me know if it isn't.

**Comment by egthomas** [comment]
Well that was an innocuous little typo; now it should really be fixed (actually grabbed a map file derived from a grid file with extended power data to verify).

**Comment by mts299** [comment]
YAY!


So the only other bugs I can see are:
- [ ] -t not working as it should
- [ ] map_plot segfaults on incorrect file (the other plotting functions do not)

**Comment by mts299** [comment]
> Can you remind me how you produced the map_plot segfault?

Sorry grid_plot also segfaults:
` map_plot -png -st 6:00 -et 7:00 -tn -mag -pwr -modn -pot -fcoast -coast -xkeyp -logo -grd -imf -time -hmb -fit -ctr -xkey_path ~/ -xkey rainbow.key not_a_real_map_file.map`
Segmentation fault (core dumped)

`grid_plot -png -st 6:00 -et 7:00 -tn -mag -pwr -fcoast -coast -xkeyp -logo -grd -time -xkey_path ~/ -xkey rainbow.key not_a_real_grd_file.grd`
Segmentation fault (core dumped)

Where other plotting methods do not:
` time_plot -png -ex 3:00 -gs -srng 35 -a -erng 60 -b 5 not_a_real_fitacf.fitacf > sas_time.png`
file not_a_real_fitacf.fitacf not found

> So it sounds like the -d and -t options are only useful in conjunction with the -stdout option. The command-line documentation can be updated to reflect that.

Sounds good, in future improvements we should also look at option combinations either working or giving errors. I think `-t` and `-d` should work with `-png` type options. However, I did notice if you put `-swd` and `-pwr` in the same command line then it only plots one of them. We may want a warning or error for those types of cases. Again this is out of the scope of the PR.

**Comment by mts299** [comment]
Looks good to me! 

Not sure if there is any other binaries to test or other test cases I can do.

**Comment by egthomas** [comment]
I think you've done a very thorough job of testing this - thanks!

**Pull request merged**
