### PR TITLE
Elevation statistics tool

### PR DESCRIPTION
**Pull request by aburrell**
Created a tool to count the number of elevation angle observations with potentially realistic values.  To test, try a radar that has and another that doesn't have elevation angles.  This, unfortunately, doesn't identify garbage values that are within a potentially realistic range.

`find_elvstat 20000131.2200.00.hal.fitacf3`

Yields:
```
Opening file:20000131.2200.00.hal.fitacf3
0 positive elevation angles below 90 degrees
```

While `find_elvstat ~/Programs/Data/SuperDARN/Downloads/20170105.1001.00.lyr.fitacf3`

Yields:
```
Opening file:20170105.1001.00.lyr.fitacf3
39809 positive elevation angles below 90 degrees
```

### CODE REVIEW

**Comment by ksterne** [comment]
Sorry it's taken a bit!  This is a nice feature to add in and I got the binary to work fairly easily.  I had a few general comments or questions that aren't specific to any line so I thought I would post them here.  Feel free to point me to a line in the code of somewhere that is relevant though.  First, are you able to easily add in some info for the `--help` option?  The option is there in the binary, but it doesn't seem to have anywhere to go.  Maybe it was a forgotten copy of a `~/doc/` directory in the main binary folder?

Second and much more minorly, I wasn't able to reproduce the results for the `20170105.1001.00.lyr.fitacf3` file.  But this could be from a different version of RST.  I used the 5.0 release to generate a fitacf3 and got `22517` for the result.  Again, this is likely different input and not an issue with this binary, but it would be good to make sense of that.  @aburrell, are you able to confirm this number with a more recently generated fitacf3 file?

**Comment by ksterne** [comment]
@aburrell, giving this a bump to see if you're able to add in a few things, mostly the results for the `--help` option when running the binary.

**Comment by ksterne** [comment]
Hey @aburrell, do you think you'll be able to check this out?  If you don't think you'll be able to look at adding `--help` results I can look into making a suggestion of what that would look like.

**Comment by egthomas** [comment]
@ksterne I think @aburrell has been out on travel, so you may need to allow some more time for her to reply.

**Comment by ksterne** [comment]
Not a problem!  I'm certainly patient on this, especially since it took my several months to initially review it.  Just trying to put it at the top of the e-mail to try to get attention.  But I understand there can be hotter burning fires that need to be put out, especially after being on travel.

**Comment by aburrell** [comment]
Hey @ksterne, I am now back from Japan and recovered from COVID.  Unfortunately that means I have a bunch of stuff to catch up on.  I will try to get to this in a week or so.

**Comment by egthomas** [comment]
@aburrell this looks good to me - I just added an XML documentation file so that `find_elvstat --help` will show something meanginful.  Please let me know if I made any mistakes or if the description should be changed.

**Review by egthomas — APPROVED** [review]

**Comment by aburrell** [comment]
Thanks @egthomas this looks good to me!

**Comment by aburrell** [comment]
@egthomas if I remember correctly, I am *not* supposed to merge this.  Correct?

**Comment by pasha-ponomarenko** [comment]
It looks like there is another reviewer, Kevin.

**Pull request merged**
