### PR TITLE
Updating radar hdw.dat Geo locations

### PR DESCRIPTION
**Pull request by egthomas**
This pull request (which is targeted at the `feature_hdw_update` branch and NOT `master` or `develop`) updates the geographic latitude and longitude locations in each radar's `hdw.dat` file based on a Google Earth search, performed primarily by an undergraduate student at Dartmouth College earlier this year.  These new radar locations are based on the midpoint of the main antenna array, and also helped us identify an incorrect sign on the Y-offset of the interferometer array for three radar sites:

- EKB
- KSR
- SAN

Note that we were unable to locate a few radars via satellite imagery, so the following radars have not had their locations modified:

- DCN
- HAL
- LYR
- SCH
- SPS

Most radar locations have changed by < 1 km in terms of great circle distance, however there are 8 sites which were incorrect by > 1 km (and 3 sites which were incorrect by > 5 km).  We will be contacting PIs directly for approval of these changes, but since #455 is already open on this repository it made the most sense to go ahead and use the new `hdw.dat` file format.

### CODE REVIEW

**Comment by pasha-ponomarenko** [comment]
Hi Evan!
Just want to piggy-back on oyur pull request: according to Oleg, EKB array separtion values are  0.0, 56.4, -3.8.

Cheers,
Pasha

**Comment by pasha-ponomarenko** [comment]
The previous EKB XYZ offests were jusd carbon-copied from BKS.

**Comment by egthomas** [comment]
Thanks @pasha-ponomarenko!

**Comment by pasha-ponomarenko** [comment]
Oh, and the tdiff is also copied from BKS! 
The actual value is close to -(7...8) ns (see page 8 in https://doi.org/10.1016/j.polar.2020.100628). I guess -0.008 would be a good number for EKB tdiff.

**Comment by ksterne** [comment]
This was probably a really cool project and interesting that a couple of radars are being corrected on interferometer placement!  Though, the lat/lon updates rely on the accuracy of Google Earth's satellite imagery mapping since the precision in the lat/lon figures are being increased.  Also, is the mapping not consistent between Google Earth and Google Maps?  I found errors in the figures for each of the VT radars when checking this with Google Maps.  The errors probably aren't large (probably < 1km), but each of them didn't fit to the description of being at the middle of the main array.

**Comment by mts299** [comment]
Should we just move this to the hdw repo or close this if its not needed?

**Pull request closed without merging**
