### PR TITLE
stripping licensing lines from .c, .h and .pro files

### PR DESCRIPTION
**Pull request by sshepherd**
Each .c, .h and .pro file contains ~20 lines of licensing information. These lines have been stripped out and replaced with "see license.txt", which exists in the top-level rst directory.

### CODE REVIEW

**Comment by egthomas** [comment]
Also looks like you've added a new file called "somefile.txt" to one of the AACGM_v2 directories.  Was this for the testing that Kevin asked for previously?

**Comment by sshepherd** [comment]
I can't seem to find that file. Can you see which directory it's in? I
doubt that it is anything that is needed. Probably something left over from
my lack of git expertise...

**Comment by egthomas** [comment]
Hopefully this link works:

https://github.com/SuperDARN/rst/blob/fbac8e415511452e6edbdf15ae9d3f6b07ca6e44/codebase/analysis/src.bin/aacgm_v2/aacgm_test.1.0/some_file.txt

**Comment by sshepherd** [comment]
Yes, that was probably left over from when I was testing the output file;
now called expected.txt. It can be deleted. Sorry for the clutter....

**Comment by egthomas** [comment]
I've deleted the extra file, but also just noticed there are ~20 files where "License" is misspelled as "Licence" and Rob's script to insert the old RST license clearly failed.

**Comment by sshepherd** [comment]
What do these files have for a license?

**Comment by egthomas** [comment]
Here's an example:

```
/* iqidl.c
   ======== 
   Author R.J.Barnes
*/

/*
 $Licence$
*/
```

**Comment by sshepherd** [comment]
We can either leave them or I can replace with the standard line.

**Comment by egthomas** [comment]
Simon and I agreed to close this pull request for now and try again later with some modifications to his script (ie catching files with typos in the license / header text, handling lines with more than 120 characters, etc.).

**Pull request closed without merging**
