### PR TITLE
Misc bug fixes to fitacfserver and map_addimf

### PR DESCRIPTION
**Pull request by egthomas**
This pull request fixes two bugs (in `fitacfserver` and `map_addimf`) and renames the `rst.version` file to make it hidden and de-clutter the root directory.

To test the [fitacfserver](https://superdarn.github.io/rst/superdarn/src.bin/tk/tcpip/fitacfserver/index.html) changes, try serving a `fitacf`-format file on a system-assigned local port, eg:

`fitacfserver -r yyyymmdd.hhmm.ss.rad.fitacf`

The system-assigned port number will be stored in the file `port.id`.  You can then use [fitacfclient](https://superdarn.github.io/rst/superdarn/src.bin/tk/tcpip/fitacfclient/index.html) or the [Java real-time client](https://github.com/SuperDARN/java_realtime) to display the fitted line-of-sight data.  On the develop branch however, the system-assigned port number is not stored in `port.id` (I see `0` when testing locally).

The second bug fix is to [map_addimf](https://superdarn.github.io/rst/superdarn/src.bin/tk/tool/map_addimf/index.html) when using CDF files from the Ace or Wind spacecraft as the solar wind input, and is related to allocating memory for the new Vx and Kp fields.  This issue and solution was originally identified by Bill Bristow.

### CODE REVIEW

**Comment by ecbland** [comment]
I've just tested the `map_addimf` portion of this PR. I get a segfault on `develop` but it works fine on this branch.

**Comment by ecbland** [comment]
Ok, onto the `fitacfserver` part of this PR. On this branch I get a non-zero `port.id` 👍

I've never used `fitacfclient` before and need some help. I did look at the documentation but I can't determine what the `host` should be if I'm just reading a random fitacf file on my computer. @egthomas could you please give me a minimal working example to try?
```
fitacfserver -r yyyymmdd.hhmm.ss.rad.fitacf
(then what...?)
```

**Comment by egthomas** [comment]
@ecbland sure, no problem.  Depending on your setup, you should probably be able to use either `localhost` or `127.0.0.1` for the `host`.  So with `fitacfclient` you should be able to use:

`fitacfclient localhost [port number from port.id file]`

or with `fitacfclientscan` you can use:

`fitacfclientscan localhost [port number from port.id]`

or with the Java real-time display (after downloading and compiling as described in the README instructions):

`java FitACFDisplayApp -n [radar name] -p [port number from port.id] localhost`

**Comment by ecbland** [comment]
Thanks @egthomas ! I had already tried with localhost but I must have done something else wrong because it didn't work the first time. Anyway, it's working now so I think this PR is ready to merge. 

Special thanks for the `map_addimf` fix - I needed to use that yesterday, so this bugfix saved me a lot of time 💯

**Pull request merged**
