### PR TITLE
Adding AACGM_v2 DLM functionality

### PR DESCRIPTION
**Pull request by egthomas**
This pull request introduces DLM functionality for 4 functions from the AACGM_v2 library:

1. AACGM_v2_GetDateTime
2. AACGM_v2_SetDateTime
3. AACGM_v2_SetNow
4. AACGM_v2_Convert

These should fully replicate the parameters and keywords of the equivalent IDL routines while providing much faster processing time.  Comparisons can be made with Simon's online calculator located here:

http://sdnet.thayer.dartmouth.edu/aacgm/aacgm_calc.php

### CODE REVIEW

**Comment by egthomas** [comment]
Note that `AACGM_v2_SetNow()` requires the bug fix included in #65 to function properly.

**Comment by egthomas** [comment]
Not sure if anyone has taken a look at this in the past month but I just did a comparison between using AACGM-v2 to plot a map of the northern hemisphere in geomagnetic coordinates both with and without the new DLM capability introduced in this pull request.  

With the new DLM it took ~3s and without the DLM it took ~13s to draw all of the coastlines.  So by merging this pull request we would receive a 4x increase in speed when converting between geographic and geomagnetic coordinates in IDL (I assume a similar increase would be observed with the MLT calculation as well).

**Comment by egthomas** [comment]
master branch:
```
IDL> help,/dlm,'aacgmdlm'                                             
% Unknown dynamically loadable module: aacgmdlm.
IDL> aacgm_v2_setnow()             
% Compiled module: CALDAT.
       0
IDL> aacgm_v2_setdatetime(2017,1,1,0,0,0)                                  
       0
IDL> aacgm_v2_getdatetime(year,month=mo,day=dy,hour=hr,minute=mt,second=sc)
       0
IDL> print,year,mo,dy,hr,mt,sc                                             
    2017       1       1       0       0       0
IDL> in_lat = findgen(10)*180./10.-90.                                     
IDL> in_lon = findgen(10)*360./10.                                         
IDL> height = replicate(300.,10)
IDL> aacgm_v2_convert(in_lat,in_lon,height,out_lat,out_lon,r)              
% Compiled module: FACTORIAL.
       0
IDL> for ii=0,9 do print,in_lat[ii],in_lon[ii],out_lat[ii],out_lon[ii]     
     -90.0000      0.00000      -75.024449       18.043764
     -71.8917      36.0000      -68.569543       67.056290
     -53.8251      72.0000      -63.334428       122.77228
     -35.8254      108.000      -49.095665       178.28721
     -17.8923      144.000      -29.312895      -141.46344
      0.00000      180.000      -12.713090      -106.91932
      17.8923      216.000       23.158844      -74.552977
      35.8254      252.000       45.149712      -40.578818
      53.8251      288.000       62.837328       8.2942609
      71.8917      324.000       74.858635       59.087874
```

feature/aacgm_v2_dlm branch without v2-updates bugfix:  (setnow fails without commit 2c9ae60)
```
IDL> help,/dlm,'aacgmdlm'                                             
** AACGMDLM - AACGMDLM (not loaded)
    Version: 2.0, Build Date: MAY 2017, Source: R.J.Barnes (JHU/APL) & E.G.Thomas (Dartmouth)
    Path: /jumbo/superdarn/evan/test_rst4/rst/dlm/aacgmdlm.so
IDL> aacgm_v2_setnow()                                                     
% Loaded DLM: AACGMDLM.

Date range for AACGM-v2 is [1900 - 2020)

          -1
IDL> aacgm_v2_setdatetime(2017,1,1,0,0,0)                                  
           0
IDL> aacgm_v2_getdatetime(year,month=mo,day=dy,hour=hr,minute=mt,second=sc)
           0
IDL> print,year,mo,dy,hr,mt,sc                                             
        2017           1           1           0           0           0
IDL> in_lat = findgen(10)*180./10.-90.                                     
IDL> in_lon = findgen(10)*360./10.                                         
IDL> height = replicate(300.,10)                                           
IDL> aacgm_v2_convert(in_lat,in_lon,height,out_lat,out_lon,r)              
           0
IDL> for ii=0,9 do print,in_lat[ii],in_lon[ii],out_lat[ii],out_lon[ii]     
     -90.0000      0.00000      -75.024449       18.043763
     -72.0000      36.0000      -68.569545       67.056282
     -54.0000      72.0000      -63.334435       122.77227
     -36.0000      108.000      -49.095662       178.28721
     -18.0000      144.000      -29.312894      -141.46344
      0.00000      180.000      -12.713090      -106.91932
      18.0000      216.000       23.158843      -74.552977
      36.0000      252.000       45.149713      -40.578818
      54.0000      288.000       62.837329       8.2942610
      72.0000      324.000       74.858632       59.087870
```

feature/aacgm_v2_dlm branch with v2-updates branch: (setnow works)
```
IDL> help,/dlm,'aacgmdlm'                                             
** AACGMDLM - AACGMDLM (not loaded)
    Version: 2.0, Build Date: MAY 2017, Source: R.J.Barnes (JHU/APL) & E.G.Thomas (Dartmouth)
    Path: /jumbo/superdarn/evan/test_rst4/rst/dlm/aacgmdlm.so
IDL> aacgm_v2_setnow()                                                     
% Loaded DLM: AACGMDLM.
           0
IDL> aacgm_v2_setdatetime(2017,1,1,0,0,0)                                  
           0
IDL> aacgm_v2_getdatetime(year,month=mo,day=dy,hour=hr,minute=mt,second=sc)
           0
IDL> print,year,mo,dy,hr,mt,sc                                             
        2017           1           1           0           0           0
IDL> in_lat = findgen(10)*180./10.-90.                                     
IDL> in_lon = findgen(10)*360./10.                                         
IDL> height = replicate(300.,10)                                           
IDL> aacgm_v2_convert(in_lat,in_lon,height,out_lat,out_lon,r)              
           0
IDL> for ii=0,9 do print,in_lat[ii],in_lon[ii],out_lat[ii],out_lon[ii]     
     -90.0000      0.00000      -75.024449       18.043763
     -72.0000      36.0000      -68.569545       67.056282
     -54.0000      72.0000      -63.334435       122.77227
     -36.0000      108.000      -49.095662       178.28721
     -18.0000      144.000      -29.312894      -141.46344
      0.00000      180.000      -12.713090      -106.91932
      18.0000      216.000       23.158843      -74.552977
      36.0000      252.000       45.149713      -40.578818
      54.0000      288.000       62.837329       8.2942610
      72.0000      324.000       74.858632       59.087870
```

**Comment by ksterne** [comment]
Similarly, any concerns with needing to reprocess data here?  I don't think there are, but wanted to check.

**Pull request merged**
