### PR TITLE
Phi diff fix for Fitacf 3.0 

### PR DESCRIPTION
**Pull request by mts299**
This PR is to address issue #189 pointed out by Bill. @pasha-ponomarenko suggested some other changes to Bill's solution to reduce code redundancy.

### CODE REVIEW

**Comment by mts299** [comment]
Here is my test: 

`make_fit -fitacf-version 3.0 20180624.0001.00.sas.rawacf > reversed_phidiff_fix.sas.fitacf`
Edit rst/tables/superdarn/hdw/hdw.dat.sas phase sign to -1 (column 12)

`make_fit -fitacf-version 3.0 20180624.0001.00.sas.rawacf > normal_phidiff_fix.sas.fitacf`
`time_plot -e -png -st 00:00 -et 02:00 normal_phidiff_fix.sas.fitacf > normal_phidiff_fix.sas.png`
`time_plot -e -png -st 00:00 -et 02:00 reversed_phidiff_fix.sas.fitacf > reversed_phidiff_fix.sas.png`
change rst/tables/superdarn/hdw/hdw.dat.sas phase sign to 1 (column 12)

Before phase sign change: 
normal_phidiff_fix sas

After phase sign change:
reversed_phidiff_fix sas

**Comment by mts299** [comment]
Here is a description of @pasha-ponomarenko fix: 
By the way, after contemplating this issue for a while I started to think that the more universal fix would be to apply the correction directly to XCF (i.e. to multiply the imaginary part by phidiff) before or while calculating cross-phase. In this case, we cover two ways of calculating elevation: (1) directly from "unfitted" lag 0 x-phase and (2) from fitting a linear function to x-phase. Both ways are currently implemented in FITACF3.0 for testing purposes with the results stored in fit.elv and fit.elv_high, respectively.

**Comment by mts299** [comment]
Would anyone like to test this branch?

**Comment by mts299** [comment]
*Poke Poke*

**Comment by egthomas** [comment]
Tested and does appear to correctly handle a negative value of `phidiff` for FITACF 3.0 results (broadly consistent with 2.5).

**Pull request merged**
