### PR TITLE
feature/elevation_library

### PR DESCRIPTION
**Pull request by egthomas**
As proposed in #150, this pull request is the first of 3 steps in updating the elevation algorithms in the RST.  This pull request simply moves the elevation angle routines out of the `fitacf.2.5` library and into a new `elevation.1.0` library, reducing the amount of duplicated code between `make_fit`, `make_fitex2`, and `make_lmfit`.  This pull request also deletes the `fitcomp.1.0` binary which was introduced by AJ and previously resided in the testing directory.  

**Note that, in contrast to #150, this pull request does not change any FITACF 3.0 behavior.**

To test, compare the output of `make_fit` using this branch (`feature/elevation_library`) and the target branch (`feature/elevation`) to make sure the calculated parameters (particularly the elevation angles) are identical.  Please remember to also try the `-old_elev` option so we can be sure all of the algorithms have been handled correctly.

### CODE REVIEW

**Comment by ecbland** [comment]
Something is wrong when using `-old_elev` on the `feature/elevation_library` branch. The elevation angles for a particular scan are identical or zero in all range gates, and the values are all around 320deg. For example, after running `make_fit -old_elev 20180101.0201.00.sas.rawacf` on this branch, the first few sets of elevation angles are:
```
        float   "elv" [26]=
                326.487640,     326.487640,     326.487640,     326.487640,     0.000000, 326.487640,     326.487640,     326.487640,     326.487640,     326.487640,       326.487640,     326.487640,     326.487640,     326.487640,     326.487640,       326.487640,     326.487640,     326.487640,     326.487640,     326.487640,       326.487640,     326.487640,     326.487640,     326.487640,     326.487640,       326.487640
        float   "elv_low" [26]=
                322.689575,     322.689575,     322.689575,     322.689575,     0.000000, 322.689575,     322.689575,     322.689575,     322.689575,     322.689575,       322.689575,     322.689575,     322.689575,     322.689575,     322.689575,       322.689575,     322.689575,     322.689575,     322.689575,     322.689575,       322.689575,     322.689575,     322.689575,     322.689575,     322.689575,       322.689575
        float   "elv_high" [26]=
                322.685944,     322.685944,     322.685944,     322.685944,     0.000000, 322.685944,     322.685944,     322.685944,     322.685944,     322.685944,       322.685944,     322.685944,     322.685944,     322.685944,     322.685944,       322.685944,     322.685944,     322.685944,     322.685944,     322.685944,       322.685944,     322.685944,     322.685944,     322.685944,     322.685944,       322.685944
--
        float   "elv" [27]=
                321.073059,     321.073059,     321.073059,     321.073059,     0.000000, 321.073059,     321.073059,     321.073059,     321.073059,     321.073059,       321.073059,     321.073059,     321.073059,     321.073059,     321.073059,       321.073059,     321.073059,     321.073059,     321.073059,     321.073059,       321.073059,     321.073059,     321.073059,     321.073059,     321.073059,       321.073059,     0.000000
```

**Comment by mts299** [comment]
Should we not push #93 first before this one or close it if this is inclusive of #93? Just want to make sure we don't make the same mistake as #150

**Comment by egthomas** [comment]
@ecbland I am not able to reproduce the behavior you're seeing with the `20180101.0201.00.sas.rawacf` file.  Here are the results for the first record when using the `feature/elevation_library` branch with the new algorithm (ie the default on this branch):

```
	float	"elv" [26]=
		15.673336,	17.631748,	17.816549,	17.635073,	0.000000,	36.817116,	1.575871,	5.646965,	36.758156,	2.269271,	36.677517,	36.595898,	33.205273,	33.594261,	34.747746,	34.516708,	35.768650,	36.174866,	36.399662,	36.253185,	36.377754,	36.335415,	0.753033,	34.967369,	36.381065,	9.199759
	float	"elv_low" [26]=
		18.546078,	19.581770,	18.722235,	19.489710,	0.000000,	4.587507,	4.285385,	6.617346,	36.891193,	4.430798,	36.900051,	36.828205,	34.557636,	34.555576,	35.182369,	35.000084,	36.044178,	36.383575,	36.640842,	36.430912,	36.592575,	36.651611,	3.812697,	35.769344,	36.880219,	12.611526
	float	"elv_high" [26]=
		12.145173,	15.439897,	16.862774,	15.563227,	0.000000,	36.365799,	36.793629,	4.471005,	36.624622,	36.849335,	36.453579,	36.362061,	31.795046,	32.604366,	34.307533,	34.026371,	35.490936,	35.964912,	36.156826,	36.074554,	36.161625,	36.016365,	36.793549,	34.146244,	35.874775,	3.212951
```

and here is the output when using the `-old_elev` option on the same branch:

```
	float	"elv" [26]=
		15.673336,	17.631748,	17.816549,	17.635073,	0.000000,	36.817116,	1.575871,	5.646965,	36.758156,	2.269271,	36.677517,	36.595898,	33.205273,	33.594261,	34.747746,	34.516708,	35.768650,	36.174866,	36.399662,	36.253185,	36.377754,	36.335415,	0.753033,	34.967369,	36.381065,	9.199759
	float	"elv_low" [26]=
		18.546078,	19.581770,	18.722235,	19.489710,	0.000000,	4.587507,	4.285385,	6.617346,	36.891193,	4.430798,	36.900051,	36.828205,	34.557636,	34.555576,	35.182369,	35.000084,	36.044178,	36.383575,	36.640842,	36.430912,	36.592575,	36.651611,	3.812697,	35.769344,	36.880219,	12.611526
	float	"elv_high" [26]=
		12.145173,	15.439897,	16.862774,	15.563227,	0.000000,	36.365799,	36.793629,	4.471005,	36.624622,	36.849335,	36.453579,	36.362061,	31.795046,	32.604366,	34.307533,	34.026371,	35.490936,	35.964912,	36.156826,	36.074554,	36.161625,	36.016365,	36.793549,	34.146244,	35.874775,	3.212951
```

Now looking at some data from Zhongshan (one of the radars where this new algorithm does have a significant impact), again looking at the elevation angles from the first record of `20180101.0201.00.zho.rawacf` using this branch with the new algorithm:

```
	float	"elv" [4]=
		14.742957,	13.727460,	13.904100,	0.000000
	float	"elv_low" [4]=
		6.635345,	7.717237,	10.236467,	0.000000
	float	"elv_high" [4]=
		20.166819,	18.086718,	16.906761,	0.000000
```

And with this branch using the `-old_elev` option:

```
	float	"elv" [4]=
		31.018570,	30.523945,	30.608408,	0.000000
	float	"elv_low" [4]=
		27.750570,	28.089052,	29.000418,	0.000000
	float	"elv_high" [4]=
		33.995670,	32.792023,	32.142162,	0.000000
```

which, as expected, disagree with one another.  The `-old_elev` results do however match the results when using the `develop` branch.

**Comment by ecbland** [comment]
@egthomas That's a worry (at my end). I'll take another look at it. 

What's the priority with this PR, in relation to @mts299 's comment?

**Comment by egthomas** [comment]
@ecbland as I proposed in https://github.com/SuperDARN/rst/pull/150#issuecomment-460285345, this pull request should be merged into `feature/elevation` before `feature/elevation` is merged into `develop` in #93.

The purpose of this pull request was to break #150 into multiple pieces to reduce the testing burden of each new feature (eg implementation of @sshepherd's 2017 algorithm vs consolidation of all of the algorithms into a single library vs implementation in FITACF 3.0).

**Comment by egthomas** [comment]
So this is a band-aid solution, but I added a counter to the while loop near the end of `elev_goose.c` to limit the number of 2pi phase iterations to 10 and thus prevent the infinite looping scenario described in #185.  This probably isn't ideal, but the algorithm published in [Shepherd [2017]](https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1002/2017RS006348) (which is made the default by the parent branch) correctly handles the multiple-dimension offset of the interferometer array and should be used anyways.

The particular dat file I've been using to test this solution is `1994111000g.dat` (specifically the beam 15 record at 00:41:25 UT).  The `-old_elev` option for `make_fit` is necessary to ensure the `elev_goose` code is used to calculate the elevation angles for testing purposes.

**Comment by ecbland** [comment]
I tested this on another computer and got the same behaviour (elevation angles of ~300 degrees on the `feature/elevation_library` branch). Very odd. Could someone else please test this while I go further down the rabbit hole?

**Comment by egthomas** [comment]
@ecbland are you seeing this large elevation angle behavior both with and without the `old_elev` option on this branch?  The two cases should both produce the same output for SAS - if they are different that may help identify the problem.

**Comment by ecbland** [comment]
> are you seeing this large elevation angle behavior both with and without the old_elev option on this branch? 

It occurs only when I use the `-old_elev` option on the `feature/elevation_library` branch.

**Comment by ecbland** [comment]
Ok, I think I have identified the problem! I have just made a fresh clone of RST with just the `feature/elevation_library` branch, and the elevation angles are now in agreement. I think the process of moving the elevation angle algorithms to other directories caused problems for git when switching between branches (e.g. deleted/renamed files are not actually deleted when switching to the new branch). I remember a discussion about this at the 2018 DAWG meeting in France. 

Ultimately this was user error (i.e. me), but a valuable lesson indeed. I'm still not sure exactly what routine produced the nonphysical elevation angles, but I think I've seen enough to be convinced that the code itself is not the problem. 

So, before I merge this, how will git handle the restructured directories when (1) this branch is merged into `feature/elevation`; and (2) `feature/elevation` is merged into `develop`?

**Comment by egthomas** [comment]
@ecbland glad you got things working!  I just tried pulling this branch into `feature/elevation` locally, and the various `elevation*.c` files in the `fitacf.2.5` directory have disappeared and the `elevation.1.0` directory is present.  But just to be safe, any time a new branch is merged I would strongly recommend performing a fresh clone / download of the repository to make sure no leftover files cause issues when changing branches.

**Comment by ecbland** [comment]
I've tested this for `sas`, `zho` and `gbr`, which represent the three distinct cases in the elevation angle calculation. Everything is working as expected. 

I think this is ready to merge, unless @egthomas wants to respond to https://github.com/SuperDARN/rst/issues/185#issuecomment-503249588 first.

**Comment by egthomas** [comment]
Fixing the `elev_goose` bug is well beyond the original scope of this pull request, so my feeling is the loop counter is an acceptable short-term fix until a more permanent solution is implemented by @sshepherd or someone else.  Such a fix should be easier to implement once this pull request and then the `feature/elevation` branch are merged.

**Pull request merged**
