### PR TITLE
Deleting RST test folder

### PR DESCRIPTION
**Pull request by mts299**
As discussed in Issue #180, this folder is not needed and may cause more
pain than worth.

### CODE REVIEW

**Comment by egthomas** [comment]
Only the `fitcomp` binary in the `testing` folder was added by AJ for his paper - most of the others serve valid purposes for comparing two raw/fit files or testing file integrity.  The `map_potential` folder probably could go unless @sshepherd has any objections.

Also, I think `fitcomp` is already pending deletion in #217.

**Comment by mts299** [comment]
@egthomas Do you know what the issue is with Travis CI push test? 
`The command "sudo apt-get -qq update" failed and exited with 100 during .`
This is the error is reported in the details.

**Comment by mts299** [comment]
@egthomas Sorry, I will revert and delete those.

**Comment by mts299** [comment]
@egthomas I am going to close this PR and get rid of the branch and if `map_potential` testing can be deleted then we can open a new PR. Didn't realize this was duplicated.

**Comment by egthomas** [comment]
@mts299 no worries, I vaguely recall that `fitcomp` was deleted in the elevation branch because of some kind of conflict

**Pull request closed without merging**
