### PR TITLE
4.1/release

### PR DESCRIPTION
**Pull request by ksterne**
This serves as the 4.1 release pull request.

I believe the first order of business is to get the 4.1 release branch to compile.  From a fresh install, I'm getting an error in the grid_plot.c code at:

https://github.com/SuperDARN/rst/blob/a51c6fa3706ef23569b05e6de9b720fc57195e0d/codebase/superdarn/src.bin/tk/plot/grid_plot.1.12/grid_plot.c#L904

Here there are only two arguments where the make_fov.c function lists 3 arguments should be passed.  This is also confusing since there are make_fov.[ch] files in grid_plot, fov_plot, field_plot, and map_plot.

Since this is probably related to #52 or #100, @egthomas, @sshepherd can you comment on why this is breaking potiently apply the bugfix directly to the 4.1/release branch?

### CODE REVIEW

**Comment by ksterne** [comment]
Whoops, I guess that's what I get for trying to get back to work after being out for the last week without going into the office.  I see #109 fixes the exact issue I noted above.  I've cherry picked the merge into the release branch and see that it's compiling now.

Sorry @egthomas, I thought the merge conflict was fixed when #52 and #100 were merged in.  I didn't realize there was an additional changed that needed to happen.

So, I guess for now, test this branch as much as possible.

**Comment by ksterne** [comment]
Also wanted to catch up here and ask if we still want this to merge in on Dec. 5th as previously scheduled or should we delay it a week (week of AGU) to allow for more testing?

**Comment by pasha-ponomarenko** [comment]
If noone objects, I would give it an extra week and see how it goes...

**Comment by ksterne** [comment]
So, I didn't realize this in testing for #100, but I think some of the map functions aren't backwards compatible with map files generated using the old (map v1 or 0.9?) code.  For example, take any uncompressed map file that was generated with the old code and try running:  `map_ascii filename` and you'll get an error reading file.  

I think this comes down to the cnvmap library's `readmap.c` file where additional parameters were added to `sname` and `stype` variables.  I *think* there are two places in the code that deal with previous backwards compatibility [here](https://github.com/SuperDARN/rst/blob/a138925ae631805acd8876e0dc60e79540a6343a/codebase/superdarn/src.lib/tk/cnvmap.1.17/src/readmap.c#L193-L200) and [here](https://github.com/SuperDARN/rst/blob/a138925ae631805acd8876e0dc60e79540a6343a/codebase/superdarn/src.lib/tk/cnvmap.1.17/src/readmap.c#L249-L256).  I think the only thing the for loop is doing is checking to make sure all of the `sdata` fields are populated.  The if statements really do the job of checking to make sure the sdata fields are populated before trying to assign variables.

I've made a local change where the for loop extends to 24, 24, and 30 as well as added "if not null" statements to 23, 24, and 30 and things appear to clear up for running map_ascii.  I haven't looked at other binaries that use this library, so it might not be the best change.

I write this here because I wonder if @sshepherd or anyone else has any comments on backwards compatibility and if the changes I noted seem to be good?  Any thoughts or other problems with backwards compatibility with map v2 that anyone can notice?  Maybe it's just my own specific use case.

**Comment by egthomas** [comment]
Shouldn't the name of this branch follow the naming convention of our previous release branch (i.e `release-4.1` instead of `4.1/release`)?

**Comment by ksterne** [comment]
I'd forgotten what the previous release was called and more so opted for the number first so that it was at the top of the drop down list of branches.  If it's more desired, I can remove this one and start again here.

**Comment by egthomas** [comment]
On second thought the branch name isn't particularly important as long as the version tag is correct.  I'd like to see #108 and #111 merged into this branch, and then the only thing left might be to update the doi in the readme file (can't remember if I previously used the general doi or version-specific one).

**Comment by pasha-ponomarenko** [comment]
>  I can't remember where we landed with getting things completed with -new versus -old transition being completed for this version or not. If it is, then I think we would have to delay the new release date until sometime in Jan. 2018. Really, only bugfixes should be applied to the release branch.

I confirm that it was decided to implement the old/new transition plus the switch error handling in RST4.1

**Comment by pasha-ponomarenko** [comment]
> Thinking of, is there any comment to the backwards compatibility I brought up before with grid/map(v1) and grid/map v2?

I am not familiar with this part of the code. I can try to replicate what you've done to fix the problem and see if it works on my machine.

**Comment by egthomas** [comment]
@ksterne could you create a pull request to this branch so we can see/test your fix?

**Comment by ksterne** [comment]
@egthomas, @pasha-ponomarenko, please see #112 for the change I found.  It'd be great as well if there weren't 15 `return -1` and the error code could mean something here.  But I'm sure that's for another release.

**Comment by egthomas** [comment]
So what is the release date looking like at this point?  Dec 5?  Dec 12?

I believe the doi badge in the readme file will always point to the latest version on Zenodo so that should be ok.

**Comment by ksterne** [comment]
Per @pasha-ponomarenko's note, I was going to push it back to Dec. 12th.

**Comment by ksterne** [comment]
The commit I just pushed is a leftover from #112.  It seems as though the pointer (ptr) going NULL is a usual thing, so unless there's a verbose option to introduce, I think removing this print is for the better.

**Comment by ksterne** [comment]
OK, I think we've got all of the pull requests in for now.  Let the "extensive" testing begin! Ha. Otherwise, did someone else want to hit the merge button here and write up a release note tomorrow?  We'll also need to do a master -> develop since there have been a handful of commits made on the release branch.  If no one else wants to do it, I'll do it early afternoon EST tomorrow.

**Comment by egthomas** [comment]
Not sure if others can see it but I drafted some tentative release notes a couple of weeks ago.  Are those visible? Was anything major left out?

**Comment by ksterne** [comment]
Ah, good work. I think you mentioned this and I'd forgotten about it!  I made some edits and additions there if that looks good.  The command line change on compilation's going to throw people for a bit.  It still does for me every once in a while.

**Comment by ecbland** [comment]
@egthomas Could you post a link to these release notes? I'm sure they are in an obvious place but... :)

**Comment by egthomas** [comment]
No problem:  https://github.com/SuperDARN/rst/releases

**Comment by pasha-ponomarenko** [comment]
I wrote a brief description of what is new in FITACF3, but I am not sure how to make it available.

**Comment by pasha-ponomarenko** [comment]
Also, @egthomas, can you make the first line in the comments (the one on switching from -new to -old) a bit more visible (e.g. flashing large bold red font)?

**Comment by mtwalach** [comment]
Perhaps it's worth specifying that it's IGRF12 that is used? Seeing as every other model has a version specified...

**Comment by aburrell** [comment]
Yes, I agree.

**Comment by pasha-ponomarenko** [comment]
I edited it a bit...

**Comment by egthomas** [comment]
Thanks everyone!  I was also able to copy the html documentation to a github project page whose source is now located on the `gh-pages` branch:

https://superdarn.github.io/rst/

Basically I had to set the `URLBASE` environment variable in `rst.bash` to `https://superdarn.github.io/rst` and then execute `make.build`, `make.code` and finally `make.doc` (on this release branch).  If no one objects, we can make this the default documentation we link to in the README file rather than the temporary documentation we have hosted at Dartmouth (which should also make it easier for others to maintain/update it).

**Comment by ksterne** [comment]
That's probably good to get documentation living on the git repo somewhere.  I'll have to check that out here soon.  I need to figure out how you make changes here to see how we would update the documentation, it's not obvious to me (and my git-foo is a little weak here).

Also, for those only playing along here, release date has been pushed back to Jan. 9 for now.

**Comment by ksterne** [comment]
Alright, as a bit of dejavu from about a month ago, does someone want to hit the merge button on this tomorrow?  If not, I'll do it about noon EST.  I can setup the master pull back into develop tomorrow since there's been quite a few changes here on the release branch.

**Comment by pasha-ponomarenko** [comment]
@ksterne, I believe you should take the honours...
;-)

**Comment by ksterne** [comment]
Sounds good, this will be closer to 1pm EST as I have a meeting at noon that I just remembered.

**Comment by pasha-ponomarenko** [comment]
I think we will survive an extra hour, and it will be around noon in Saskatchewan anyways...
:-P

**Comment by ksterne** [comment]
@pasha-ponomarenko, what about letting people know of the release?  Do you want to e-mail to the darn-users list so it's easily/quickly forgotten about? ;)  Any other lists that would probably be good?

**Comment by pasha-ponomarenko** [comment]
@ksterne, yep, I was going to send a warning about old/new switch to darn-users.
I am not sure about other lists.

**Comment by ksterne** [comment]
Well, there's at least the equally effective darn-pi list.

**Comment by pasha-ponomarenko** [comment]
Which I am not a member of... ALthough, I can ask Kathryn.
So, the release has been performed by now?

**Comment by ksterne** [comment]
Not quite fully.  At least not linked to the release tag that had been drafted up.  Working on that now...

**Comment by ksterne** [comment]
Or, Evan beat me to it I think.  Care to fill @pasha-ponomarenko in with the links/details?

**Pull request merged**
