### PR TITLE
Readthedocs: updated release location for RST

### PR DESCRIPTION
**Pull request by ecbland**
After proudly showing off our readthedocs documentation to a colleague, they immediately pointed out that the homepage (`index.md`) still points users to Github and the VT website to obtain RST, rather than to Zenodo. This PR corrects that information. 

@ksterne It would be good if this can sneak into the v4.4 release

EDIT: Not sure why the older commits from @ksterne show up here. I've only edited one file (`index.md`).

### CODE REVIEW

**Comment by ksterne** [comment]
Did you start from `master` or from `develop` here?  I'm guessing my commits showing up is part of the cherry-pick'ing for the `4.3.2` release.

**Comment by ecbland** [comment]
@ksterne I started from develop. If it helps I could just close this PR and start again from the 4.4 release branch? The edits are quite trivial

**Comment by ksterne** [comment]
It's probably good to start with develop to follow our usual development flow.  So that's good. We'll try to figure things out when we do the release merge.

**Comment by ksterne** [comment]
Sorry for a second comment/question, but I'm guessing the Zenodo link will always point to the latest release?  Much like how github's link for https://github.com/SuperDARN/rst/releases/latest will always take you to the most recent one.  I thought there was some kind of chicken and egg problem (sorry I've been overusing that expression this week) where you might not get a DOI until the new release is made to `master`, so you can't have that in the PR into `master` before merging it.

**Comment by ecbland** [comment]
> @ksterne [Will] the Zenodo link will always point to the latest release? 

I used the link that always points to latest release (https://doi.org/10.5281/zenodo.801458), so I think we're ok here

**Comment by mts299** [comment]
@ksterne readthedocs links to github and can build documentation based on branches and rebuild based on pushes to the branch through a webhook. However, since the links are static in the REAdME I am not sure if we can get them to auto change when we merge release branches into master branches. Hopefully, this makes sense, it a link issue not readthedocs issue haha 

Also, I don't want to add another step to release with changing links so this is why I never really bothered with bringing it up :p

**Comment by mts299** [comment]
woops wrong PR... still to early for me I guess :p

**Comment by ecbland** [comment]
Found two more files which directed the user to Github to download the software: `linux_install.md` and `mac_install.md`. These have now been updated.

**Comment by mts299** [comment]
what is the status of this PR?

**Comment by ecbland** [comment]
This was a simple update, but I got confused about why @ksterne's commits showed up. But it's ready for review in any case.

**Comment by ksterne** [comment]
OK, I think this looks good.  I'll work through the command line of merging it into `4.4-release`.  It should just be the version one that's conflicting.  Resolving the conflicts here will be good practice for when I do it for `master`.

**Pull request merged**
