### PR TITLE
Release: RST 4.7

### PR DESCRIPTION
**Pull request by ecbland**
# Release RST 4.7

- [ ] PATCH
- [X] MINOR
- [ ] MAJOR

## Deadline: 11 April
Please comment in the Pull Request conversation if you need additional time to test the release.

## Testing

- [ ] Mac OSx
- [ ] Linux deb - Debian, Ubuntu, Mint
- [ ] Linux rpm - OpenSuse, Fedora, CentOS

*Do any binaries/libraries require special attention during testing?*

Key updates in this release are
- New hardware file format (#455)
- Find frequency bands (#444)
- Data simulator updates (#436)
- Bug fixes for compilation on various systems
    - #450
    - #459
    - #462
- Anything else?

## Checklist

- [ ] Update `radar.dat` (if required)
- [x] Update hardware files (if required)
- [ ] Update `.rst.version`
- [ ] Update author list in `.zenodo.json`

## Approving the release

After testing, please state which operating system you used and what you tested.

If you found no bugs during testing, please *approve* the PR:

1. Click on `files changed` top right
2. Click on `start review` green top right  button
3. In the comment box, state which operating system you used for testing, and any other helpful information
4. Select `approve` and `submit review`

### CODE REVIEW

**Comment by egthomas** [comment]
@ecbland there were changes to `bmsep` in the five Borealis `hdw.dat` files on the `hdw` repository that should be probably captured here:

https://github.com/SuperDARN/hdw/pull/4
https://github.com/SuperDARN/hdw/commit/dfa24293106300e44dca68cf41995e4524676df9

Also, should a few status flags / end dates be updated in the `radar.dat` file to match the end dates added to some of the `hdw.dat` files (eg ADE/ADW, STO, PYK, etc)?

**Comment by pasha-ponomarenko** [comment]
Hi all! 
In order to expand the two-channel elevation calibration to all data with two channels (right now it is restricted to the stereo mode only), I would like to have the condition (offset == 0) to be removed from these locations:
https://github.com/SuperDARN/rst/blob/db5204d4f049e2e84817b6f89752fea0ad79c659/codebase/superdarn/src.lib/tk/fitacf.2.5/src/fitacf.c#L69
and 
https://github.com/SuperDARN/rst/blob/db5204d4f049e2e84817b6f89752fea0ad79c659/codebase/superdarn/src.lib/tk/fitacf_v3.0/src/fitacftoplevel.c#L174

Please let me know if there are any serious data quality concerns related to these changes.

Cheers,
Pasha

**Comment by ecbland** [comment]
> @egthomas  Also, should a few status flags / end dates be updated in the `radar.dat` file to match the end dates added to some of the `hdw.dat` files (eg ADE/ADW, STO, PYK, etc)?

Thanks for pointing this out. How do I find out what the end dates are? The hardware files show the start date for the last record but not the date the radar stopped being operational.

**Comment by egthomas** [comment]
> Thanks for pointing this out. How do I find out what the end dates are? The hardware files show the start date for the last record but not the date the radar stopped being operational.

@ecbland the lines with a `-1` status flag indicate the date/time when the radar stopped being operational, eg

```
 209  1 20140828 04:33:57   51.89  -176.63      4.0   46.0  0.00  3.24  1  1 -0.435  0.000    0.0  -69.85  0.5    0.0  10 0 110 22
 209 -1 20181017 00:00:00   51.89  -176.63      4.0   46.0  0.00  3.24  1  1 -0.435  0.000    0.0  -69.85  0.5    0.0  10 0 110 22
```

> In order to expand the two-channel elevation calibration to all data with two channels (right now it is restricted to the stereo mode only), I would like to have the condition (offset == 0) to be removed from these locations:

@pasha-ponomarenko do you mind clarifying which radars (other than the Stereo-style) are recording multi-channel data that will require separate tdiff values?  @aburrell can correct me if I'm wrong, but I believe there are plans for further updates to the tdiff capabilities to support different values for different frequencies (eg for a twofsound-style mode) if that is your concern.

**Comment by aburrell** [comment]
@egthomas is correct with the intended scope for these tdiff records and the intended design to handle frequency (and other non-channel) dependencies in tdiff.

**Comment by ecbland** [comment]
Oops, I didn't create a new branch for this release. My mistake. To avoid losing `develop` after merging, I'll close this PR and open a new one! 

@pasha-ponomarenko Could you please open a new issue to continue the discussion about the tdiff values for multi-channel data?

**Comment by pasha-ponomarenko** [comment]
@ecbland , yes, sure!

**Pull request closed without merging**
