### PR TITLE
Deleting temp and backup files

### PR DESCRIPTION
**Pull request by egthomas**
This pull request deletes a bunch of temporary and redundant backup code that clutters search results and is archived in the VTRST3.5 repository (and v3.5 of this repository).  Even the hlpstr.h file for test_lmfit is just copied from make_lmfit and is not actually informative (not to mention the wrong way of building help output).  No changes have been made to the functionality of any active code, and compilation of this branch has been successfully tested.

### CODE REVIEW

**Comment by kkotyk** [comment]
I've tested this from a clean install and it compiles no problem. I can merge this if you are done removing stuff.

**Comment by egthomas** [comment]
Yep, that should cover all of the deletions / modifications for this branch.  We may have finally run out of things to delete!

**Comment by ksterne** [comment]
@egthomas, I think that's un-possible!  There's always more to delete.  Only when you do sudo rm / can you be really sure there's nothing left to delete! ;)

**Comment by egthomas** [comment]
I did speak too soon - there are a few lines that should be removed from `build.txt` but for now they aren't causing any problems and can be dealt with later.

**Pull request merged**
