### PR TITLE
RFC warning and documentation build fixes

### PR DESCRIPTION
**Pull request by egthomas**
The main purpose of this pull request is to add a warning to the top of the RFC documentation page that the information on these pages has not been maintained/updated since the mid-2000s and the information may be incorrect or out of date (see #205, #194, etc).  There are also a couple of other bug fixes to make the existing documentation compilation process smoother.

To test, after compiling the RST with `make.build` and `make.code`, execute the command `make.doc`.  On the `develop` branch, if you navigate through the resulting html pages the index page for the RFCs will be empty ([this page on the web documentation](https://superdarn.github.io/rst/superdarn/src.doc/rfc/index.html)).  A second call to `make.doc.rfc codebase superdarn` is necessary to build the correct RFC index page.  On this branch, the RFC index page will be properly constructed and a warning will appear near the top of the page after a single execution of `make.doc`.

### CODE REVIEW

**Comment by egthomas** [comment]
Ok, after this last commit the documentation pages should be much more user friendly.  Part of the problem was that originally `src.bin` and `src.lib` were the top-level directories under `code` (now known as `codebase`), whereas now the top-level directories are `analysis`, `base`, etc.  For an example, see here:

https://web.archive.org/web/20081231150150/http://superdarn.jhuapl.edu/doc/index.html

I've therefore modified a few of the top-level documentation page headers and menu links to make them more descriptive and intuitive.  Obviously I am aware of the discussions in #210 and Emma's RST for Dummies guide, but hopefully these changes will improve the quality of the existing documentation system in the short term.  To test, see the instructions at the bottom of the original comment on this pull request.

**Comment by egthomas** [comment]
I've uploaded a temporary copy of the revised documentation here:

http://superdarn.thayer.dartmouth.edu/WG-sched/assets/doc_test/index.html

You can compare this to the existing documentation here:

https://superdarn.github.io/rst/

**Comment by egthomas** [comment]
This last commit addresses @ksterne's issue #197 with the `make_info` documentation missing several options:

http://superdarn.thayer.dartmouth.edu/WG-sched/assets/doc_test/superdarn/src.bin/tk/tool/make_info/index.html

**Comment by mts299** [comment]
Looks like fixes works when I compile the documentation.
Test 
```
make.doc
xdg-open doc/html/index.html
```

 I will Merge it now and does this solve Issue #194 #197 #205 ?

**Pull request merged**
