### PR TITLE
cnvmodel library

### PR DESCRIPTION
**Pull request by egthomas**
This pull request addresses issue #176 raised by @ksterne about duplicate code being present in the `map_addmodel` and `solve_model` binaries.  This was due to me copying most of the functions from `map_addmodel` to create the `solve_model` binary in #159.

Nearly all of the functions have been broken out of `map_addmodel.c` and `solve_model.c` into a new `cnvmodel.1.0` library.  The two functions which have not been moved into the new library (`solve_model` and `get_model_pos`) operate on different data structures and are therefore no longer identical between the `map_addmodel` and `solve_model` binaries.

No functionality has been added or changed by this pull request.

### CODE REVIEW

**Comment by mts299** [comment]
Looks like you got rid of some of the warnings: 
develop count: 128
cnvmodel_library count: 114 

All my test passed and I compared the plots produced by each test and branches to ensure there were no side effects. 

Develop:
Test 1: -o 8 -d l options
Test successful
Test 2: use cs10 model
Test successful
Test 3: use rg96 model
Test successful
Test 4: use psr10 model
Test successful
Test 5: use ts18 model
Test successful
Test 6: use ts18_kp model
Test successful
Test 7: use nointerp model
Test successful
Test 8: use noigrf model
Test successful

cnvmodel_library branch:
Test 1: -o 8 -d l options
Test successful
Test 2: use cs10 model
Test successful
Test 3: use rg96 model
Test successful
Test 4: use psr10 model
Test successful
Test 5: use ts18 model
Test successful
Test 6: use ts18_kp model
Test successful
Test 7: use nointerp model
Test successful
Test 8: use noigrf model
Test successful

**Comment by mts299** [comment]
Does anyone else want to test this branch? 
Otherwise, I can merge it.

**Comment by mts299** [comment]
@egthomas Shall I merge this branch? 

@ksterne Did you want to test it?

**Comment by egthomas** [comment]
@mts299 if you think it's ready, sure.

**Comment by mts299** [comment]
Sounds good. 

Ps. I will be testing PRs today so you may get sick of your inbox soon.

**Pull request merged**
