### PR TITLE
Correcting velocity reversal issue for Syowa radars

### PR DESCRIPTION
**Pull request by egthomas**
This pull request corrects a velocity reversal issue for Syowa South before 24-April-1996 and for Syowa East between 27-Dec-1997 and 16-Jul-1999. This was previously corrected in older versions of the software within oldfit.pro and fitropen.c but did not make it into the RST.  Rather than modify the software, this commit adds the necessary entries to the hdw.dat files for sye and sys radars.  Dieter Andre's original comments on this issue are as follows:

>Mon Jul 24 16:49:44 BST 2006
>
> Dear All.
>
>I found this important enough to send it to the whole community.
>
>Due to a hardware error the velocities were reversed for Syowa South
>before 24-April-1996 and for Syowa East between 27-Dec-1997 and
>16-Jul-1999.
>
>In the old software [fitropen.c] this was taken care by again reversing
>the velocities, but it somehow did not make it into the Radar Software Toolkit.
>
>Until this has been incorporated into RST, you can do the following
>to fix the problem [all file paths are relative to your RST home directory]:
>
>Copy  fitreadcurrent.c  to  code/src.lib/superdarn/oldfit.1.13/src
>and remake library liboldfit .
>
>Go to  code/src.lib/superdarn/idl/oldfitidl.1.02/src
>and remake library oldfitidl  .
>
>Copy oldfit.pro to code/src.idl/lib/superdarn/main.1.02 .
>
>
>Regards
>  Dieter

http://lists.le.ac.uk/mailman/private/darn-users/2006q3/000792.html

### CODE REVIEW

**Comment by egthomas** [comment]
Responding to @ksterne here, Dieter has tried contacting Sessai with no response (yet); he believes this fix was lost in translation from the older software to the RST and should be implemented in the hdw.dat files.  

Yes, this should probably be added to the hdw.dat repository as well.  Until we figure out how to handle issue #3 I suppose we can try to maintain the two in parallel.

**Comment by pasha-ponomarenko** [comment]
Sessai is away in Antarctica until 23 March. I am leaving Japan on 1 April, so I might try to see him before then, but this is not guaranteed.

**Comment by ksterne** [comment]
Hey @pasha-ponomarenko, certainly enjoy your time off...but if you cross paths with Sessai, can you check into this before you leave at the end of next week?

**Comment by pasha-ponomarenko** [comment]
Sessai has arrived to Japan just yesterday, but I will try to get in touch with him before flying back home.

**Comment by egthomas** [comment]
While hunting down old RST version release info, I came across another message on the darn-users archive indicating there may be some additional info missing from the Syowa South hdw.dat file (http://lists.le.ac.uk/mailman/private/darn-users/2001q1/000308.html):

> Thu Jan 25 10:28:41 GMT 2001
>
> Dear all,
>
>We changed Syowa South radar boresite again (+159.0 degree now)
at the end of last century (06:00:00 UTC on Dec. 31st, 2000)
(actually returned back to original one (for a period until 1998))
to start XCF observation properly in near future. (No electrical shift now.)
'interfer_pos[2]' is now 0.0 and is not true, it will be corrected
in near future.
>
>So updated ~radar/tables/superdarn/hdw/hdw.dat.j for the new RST OS is...
>
>######## Next line is for a period UNTIL 00:00:00 UTC Jan.  1st, 1999
#<span>12</span> 1998 31556736 -69.00 +39.58 0.0 +159.0 -3.33 +1.0 10.0 0.0 +1.0 -5.0 +91.96 +0.82 50.0 3
12 1999        0 -69.00 +39.58 0.0 +159.0 -3.33 +1.0 10.0 0.0 +1.0 -5.0 +91.96 +0.82 50.0 3
######## Next line is for a period SINCE 00:00:01 UTC Jan.  1st, 1999
########                       and UNTIL 05:59:59 UTC Dec. 31st, 2000
######## (boresite was electorinically shifted.)
12 2000 31557599 -69.00 +39.58 0.0 +165.0 -3.33 +1.0 10.0 0.0 +1.0 -5.0 +91.96 +0.82 50.0 3
######## Next line is for a period SINCE 06:00:00 UTC Dec. 31st, 2000
########			   UNTIL the end of year 2999....
########			added at 23:32:40 UTC Jan.  2nd, 2001 at Syowa
######## (*** interfer_pos[2] is not true yet!!! will be corrected in near future.)
12 2999 31556736 -69.00 +39.58 0.0 +159.0 -3.33 +1.0 10.0 0.0 +1.0  0.0 +91.90  0.00 50.0 3
>
>And updated entry for Syowa South in /radops/tables/hardware.dat for Radops2000
is also almost the same. Just the last parameter, max_atten(3 for Syowa),
in each line should be deleted for Radops2000.
(Actually, some relevant table files in Radops2000,
	/radops/tables/bmrtabl_j.dat, /radops/tables/cnvtabl_j.dat
	/radops/tables/invtabl_j.dat, /radops/tables/grid/invtabl_j.dat
 were also updated (returned back to the original ones.)
>
>This info is also available on our NIPR/UAP SENSU web page, and you can 
get the newest SD southern hemisphere FOVs map(gif/ps files) there.
	(open http://www.uap.nipr.ac.jp/SD/
	 and click "Syowa South boresite change in 1999 and in Dec.2000")
>
>Thanks for your attention.
>
>Best regards,
>Sessai

It looks like the boresite was changed from 159 to 165 degrees in the hdw.dat.sys file but was never changed back to 159 as of 6 UT on 31 Dec 2000 as Sessai indicated.  There is also some mention of the interferometer position information being incorrect.

**Comment by sshepherd** [comment]
Sessai's email is a bit confusing... I think we will need to ask him about it at the Workshop. Here is what I have for sys:
12 1999        0  -69.000   39.580   0.0  159.0 -3.33  1     10  0.000  1    -5.0   92.0    0.8  50.0  3  75 16
# Sessai's line from above
12 1999        0  -69.00   +39.58     0.0 +159.0 -3.33 +1.0 10.0 0.0 +1.0 -5.0 +91.96 +0.82 50.0 3
# Sessai's line from above
12 2000 31557599 -69.00 +39.58 0.0 **+165.0** -3.33 +1.0 10.0 0.0 +1.0 -5.0 +91.96 +0.82 50.0 3
# Sessai's line from above
12 2999 31556736  -69.00 +39.58 0.0 **+159.0** -3.33 +1.0 10.0 0.0 +1.0 **0.0 +91.90 0.00** 50.0 3
12 2999 31556736  -69.000   39.580     0.0  165.0 -3.33  1 10  0.000  1 -5.0   92.0    0.8  50.0  3  75 16

This seems to indicate that (1) the boresight changed and changed back but we did not update the change back and (2) the interferometer moved (Sessai confirmed this at the Leicester Workshop but didn't give me the numbers) and was not updated.

**Comment by sshepherd** [comment]
A couple of questions for the PIs or engineers of the following radars: inv, sys, sys.

The following are interferometer values from "official" hdw.dat files.

ID      X        Y         Z      tdiff
------------------------------------
inv:  +1.5  +100.0   0.0   0.000 
sye:  -5.0    +92.0 +0.8  0.000  % the email above suggests 0.0 +91.90 0.0
sys:  -5.0    +92.0 +0.8  0.000   % same here

The XYZ offsets for inv looks suspiciously like they were copied from gbr and never modified. There is a long tradition of doing just this for new radars.  @pasha-ponomarenko, while you are waiting for Evan to arrive can you ask JP, Dieter, KK, or anyone else that might know if those values are correct for inv?

Can anyone confirm that the values XYZ = (0.0 +91.90 0.0) @sessai indicated in his email from 2001 are the correct values?

**Comment by egthomas** [comment]
@kevinkrieger - can you speak to Simon's question about the inv hdw.dat file?

**Comment by kkotyk** [comment]
@egthomas I also forwarded this to Dieter.

**Comment by ksterne** [comment]
Thinking of hdw.dat files (#70, #78, #79, #72, #76), was there any movement on this issue in the last few weeks?  Anyone able to link up with Sessai to get these corrected?  #73, thinks that someone was able to make contact...

**Comment by egthomas** [comment]
I did speak to Sessai about these hdw.dat updates.  Regarding the original intent behind this pull request (implementing the software fix suggested by Dieter in the Syowa South hdw.dat file), Sessai thought that stemmed from how we used to distribute data.  Previously only the fit files generated at the radar were distributed to the community so the velocity sign fix needed to be made in the reading software rather than at the make_fit stage when going from a dat to fit file.  Now that we distribute the original dat files and users can produce fit-level data from those, I think we do need to make the change in the hdw.dat file.  Regarding the second change (to the Syowa South boresite and interferometer) I think he needed to go back to NIPR and verify what the correct values should be.

I guess the takeaway is that Sessai needed to think about it and get back to us.

**Comment by egthomas** [comment]
So it looks like Sessai et al have resurrected the old NIPR SD website.  Even though the darn-users emails cited in my earlier messages are no longer accessible, the relevant technical info is now available here:

http://polaris.nipr.ac.jp/~SD/sensu/techinfo.html

In particular, see the "SyowaSouth boresite change in Jan.,1999" and "IQ reversal periods for Syowa radars" links.

**Comment by pasha-ponomarenko** [comment]
> Syowa South Boresite was changed (6 degrees electrically) to obtain more 2-D vectors combined with Halley and Sanae radars in austral summer (January) in 1999 when all the antenae were rebuilt there. So the new hardware.dat entry for SyowaSouth is now... 

If this has been done electrically, then the elevation calculation is incorrect because the boresite direction is not perpendicular to the antanna array any more (i.e. instead of beams 0:15 one would have 2:17 or -2:13). I recall the same issue affecting BKS data where extra lengths of cable were added to each antenna in order to swing the diagram by 8 deg.
The same has been done to TIGER except the "swing" was only used during the discretionary time.

Looks like we might need to introduce yet another extra field in the hardaware file...

**Comment by egthomas** [comment]
One of Sessai's emails indicated the interferometer position had also changed, so correctly calculating elevation angles for Syowa South is probably impossible right now.

**Comment by ecbland** [comment]
Update: I emailed Sessai about this today

**Comment by mts299** [comment]
What is the status on this PR?

**Comment by ecbland** [comment]
I tried contacting the PI again a month ago, but no response. We agreed during the November telecon that changes to hardware files should be implemented in the hdw.dat repo and then copied to RST through the webhooks, so I think we should close this PR without merging. 

I hope these hardware files can be updated in the near future, and a big thankyou to @egthomas for his sustained effort regarding this important issue.

**Pull request closed without merging**
