### PR TITLE
Extending field_plot and time_plot functionality (errors, elevation angles, phi0, etc)

### PR DESCRIPTION
**Pull request by egthomas**
In response to #208, this PR adds functionality for plotting velocity errors from a fitacf-format file to `time_plot` and `field_plot`.  This PR also adds the ability to plot elevation angles using `field_plot` by adding a new field to the `RadarCell` structure (this was already implemented in `time_plot`).

### CODE REVIEW

**Comment by pasha-ponomarenko** [comment]
@egthomas, I just wonder what other parameters can be plotted? We might think about adding more...

**Comment by egthomas** [comment]
@pasha-ponomarenko as of this pull request, `time_plot` and `field_plot` allow for plotting of 

- velocity
- velocity error
- power (p_l)
- spectral width (w_l)
- elevation angle

I suppose phi0 and/or lag0 may be two other parameters worth plotting?  I'm not sure if enough people use the sigma fit of the ACFs or the XCF-derived parameters to justify adding those.

**Comment by pasha-ponomarenko** [comment]
Yep, pwr0 and phi0 would be useful and, probably, w_l_e...

**Comment by mts299** [comment]
@egthomas @pasha-ponomarenko Do you want to do this for another PR?

**Comment by pasha-ponomarenko** [comment]
Whatever is more practical... This is not that urgent.

**Comment by egthomas** [comment]
Something is screwy with the phi0 color scaling, but it's too late in the week for me to look at this any longer.

**Comment by mts299** [comment]
@egthomas can you let me know when I should test this PR.

**Comment by egthomas** [comment]
I don't plan on adding the other plotting parameters to `field_plot` since it shares a data structure with several other binaries so you can go ahead and test the changes there.  Otherwise `time_plot` is good to go except for the `phi0` color scaling - any help fixing that would be greatly appreciated.

**Comment by mts299** [comment]
@egthomas Is this PR ready to be tested again :)

**Comment by egthomas** [comment]
@mts299 yes, this PR can be tested.  There is still some issue with the phi0 color scale but at this point I can't remember exactly what it was.

**Comment by ecbland** [comment]
I think I've identified the problem with `phi0`:

Line 138 of `time_plot.1.8/fit.c`:

`if (fit->xrng !=NULL) tptr->phi0[i]=fit->rng[i].phi0;`
should be 
`if (fit->xrng !=NULL) tptr->phi0[i]=fit->xrng[i].phi0;`

**Comment by egthomas** [comment]
@ecbland thanks, nice catch!  That fixed the `phi0` plotting error.  I went ahead and added the same functionality to `field_plot` to bring it in line with `time_plot`; now `phi0`, `w_l_e` (spectral width error), and lag0 power can be plotted with either routine.  Hopefully that is not considered to be too much scope creep.

**Comment by ecbland** [comment]
Ok, I've tested this again and it's working well! This is a very nice addition to the plotting routines.

**Pull request merged**
