### PR TITLE
Updating mcm and sps hdw.dat files according to VT hdw.dat repo

### PR DESCRIPTION
**Pull request by egthomas**
This commit changes the receiver rise time of the mcm and sps radar sites from 100 to 0 microseconds as identified by Jon Klein.  This commit also fixes a sign error in the interferometer position and updates the tdiff value of the sps radar as identified by Bill Bristow.  For reference, see https://github.com/vtsuperdarn/hdw.dat/pull/4

### CODE REVIEW

**Comment by sshepherd** [comment]
This request should be accepted and merged into the current RST ASAP. These changes have been sitting for months on the hdw.dat updater repo with no action and they affect how data is processed for these radars.

**Comment by kkotyk** [comment]
Who do we need to merge this? Someone from Bill's team?

**Comment by ksterne** [comment]
This is the same as:

**Comment by ksterne** [comment]
Merging it in.  I'd gotten an e-mail a week ago from Bill wanting to make the change to the sps file.

**Pull request merged**
