### PR TITLE
Added instructions on how to contribute to RST

### PR DESCRIPTION
**Pull request by ecbland**
This pull request adds some general information to the `README.md` file to help users find out what the DAWG is working on and how to contribute to RST. 

This is in response to feedback from the SuperDARN community obtained during the AGU Fall Meeting in 2019, and also an attempt to recruit some new developers/testers. 

@ksterne We could list our names & email addresses on line 27 (if you're happy to do that). Or is there a better way to do this?

### CODE REVIEW

**Comment by mts299** [comment]
That is a nice section you got their @ecbland  ;)

**Comment by ecbland** [comment]
> That is a nice section you got their @ecbland ;)

Yes, shamelessly adapted from the pyDARN readme...thanks @mts299 😉

**Comment by egthomas** [comment]
It may not need to go in the readme or be decided with this pull request, but the procedure for generating the Zenodo/DOI citation (ie author list and order) for each release should also be formalized.  Are all past authors always included in the author list?  Only those who contributed since the previous release?  Some middle ground between those two options?  That's why I haven't updated the Zenodo page for the most recent patch release - unlike previous minor releases the approach was not quite as clear.

**Comment by mts299** [comment]
Good question @egthomas, however, to keep this PR within the scope and to avoid bloating of documentation I moved your comment to issue #272.

**Comment by ksterne** [comment]
@ecbland, what are your thoughts on including e-mail contact info for us?  I think it will increase my amount of spam, but I'm OK with adding one of my e-mail addresses (the kevintyler at vt edu one) to this.

**Comment by ksterne** [comment]
Are the permissions setup so that non-members of a list can post to that list though?

**Comment by ecbland** [comment]
> Are the permissions setup so that non-members of a list can post to that list though?

@ksterne I doubt it, although I can't see anything on the mailing list webpage related to this so I can't verify. 

As an alternative we could replace line 27 with something like "If you would like to contribute code to RST, please open a new issue on the RST github page (https://github.com/SuperDARN/rst/issues) and we will get in touch". This is future-proof, it prevents spamming both the mailing list and the DAWG chairs, and any potential developer would need a github account anyway. Thoughts?

**Comment by ksterne** [comment]
Seems as though non-members can e-mail the list...since I just did.  I don't have a problem either way.  I could see an advantage to keeping personal e-mails so that everyone doesn't get spammed in the future.  I've heard in the past the creating a github account can deter some people away.  Though if they are wanting to contribute specifically to this repo (and not just be apart of the DAWG), then they'll more than likely need to make a github account.

**Comment by ecbland** [comment]
@ksterne Ok, let's keep it with our personal email addresses then. In which case perhaps this is ready to merge if there are no other issues?

**Pull request merged**
